#!/bin/bash

# Get current date and timestamp
DATE=$(date +%Y%m%d_%H%M%S)

# Run the training command
echo "Starting training run: cc.$USER.test.$DATE"
uv run ./tools/train.py +hardware=macbook run=cc.$USER.test.$DATE trainer.total_timesteps=10000 wandb=off

echo "Training run cc.$USER.test.$DATE completed!"
