#!/bin/bash
# sweep_rollout.sh - Execute a single sweep rollout
set -e

# Parse arguments
args="${@:1}"

# Extract and validate sweep run
sweep_run=$(echo "$args" | grep -o 'sweep_run=[^ ]*' | sed 's/sweep_run=//')
if [ -z "$sweep_run" ]; then
  echo "[ERROR] 'sweep_run' argument is required (e.g., sweep_run=my_sweep_name)"
  exit 1
fi

# Extract hardware argument if present
hardware_arg=$(echo "$args" | grep -o '+hardware=[^ ]*' || true)

source ./devops/setup.env

DIST_ID=${DIST_ID:-localhost}
DIST_CFG_PATH="$DATA_DIR/sweep/$sweep_run/dist_$DIST_ID.yaml"

echo "[INFO] Starting sweep rollout: $sweep_run"
mkdir -p "$DATA_DIR/sweep/$sweep_run"

# Create initial dist file to avoid FileNotFoundError in @metta_script decorator
echo "Creating initial dist config: $DIST_CFG_PATH"
cat > "$DIST_CFG_PATH" << EOF
# Placeholder dist config - will be updated by sweep_init.py
run: null
wandb_run_id: null
EOF

# Initialize sweep
echo "[SWEEP:$sweep_run] Initializing sweep configuration..."
cmd="tools/sweep_init.py dist_cfg_path=$DIST_CFG_PATH $args"
echo "[SWEEP:$sweep_run] Running: $cmd"
if ! $cmd; then
  echo "[ERROR] Sweep initialization failed: $sweep_run"
  exit 1
fi

# Extract run ID from the dist config generated by sweep_init.py
run_id=$(grep '^run:' "$DIST_CFG_PATH" | awk '{print $2}')
if [ -z "$run_id" ]; then
  echo "[ERROR] Failed to read run ID from $DIST_CFG_PATH"
  exit 1
fi

# Training phase - use train_job config
echo "[SWEEP:$sweep_run] Starting training phase..."
# Include hardware argument if it was provided
if [ -n "$hardware_arg" ]; then
  cmd="./devops/train.sh run=$run_id dist_cfg_path=$DIST_CFG_PATH data_dir=$DATA_DIR/sweep/$sweep_run/runs $hardware_arg"
else
  cmd="./devops/train.sh run=$run_id dist_cfg_path=$DIST_CFG_PATH data_dir=$DATA_DIR/sweep/$sweep_run/runs"
fi
echo "[SWEEP:$sweep_run] Running: $cmd"
if ! $cmd; then
  echo "[ERROR] Training failed for sweep: $sweep_run"
  exit 1
fi

# Evaluation phase
echo "[SWEEP:$sweep_run] Starting evaluation phase..."
cmd="./tools/sweep_eval.py dist_cfg_path=$DIST_CFG_PATH data_dir=$DATA_DIR/sweep/$sweep_run/runs $args"
echo "[SWEEP:$sweep_run] Running: $cmd"
if ! $cmd; then
  echo "[ERROR] Evaluation failed for sweep: $sweep_run"
  exit 1
fi

echo "[SUCCESS] Sweep rollout completed: $sweep_run"
