#!/bin/bash
# sweep_rollout.sh - Execute a single sweep rollout
set -e

# Parse arguments
args="${@:1}"

# Extract and validate sweep name
sweep_name=$(echo "$args" | grep -o 'sweep_name=[^ ]*' | sed 's/sweep_name=//')
if [ -z "$sweep_name" ]; then
  echo "[ERROR] 'sweep_name' argument is required (e.g., sweep_name=my_sweep_name)"
  exit 1
fi

# Extract hardware argument if present
# This is needed for local sweeps.
hardware_arg=$(echo "$args" | grep -o '+hardware=[^ ]*' || true)

source ./devops/setup.env # TODO: Check this is the right sourcing.

# Parse distributed config path
DIST_ID=${DIST_ID:-localhost}
DIST_CFG_PATH="$DATA_DIR/sweep/$sweep_name/dist_$DIST_ID.yaml"

echo "[INFO] Starting sweep rollout: $sweep_name"

# Prepare the run for training.
# TODO: Still not sure we need the DIST_CFG_PATH here.
# TODO: Use SWEEP_DATA_DIR
echo "[SWEEP:$sweep_name] Preparing next run..."
cmd="tools/sweep_create_run.py dist_cfg_path=$DIST_CFG_PATH $args"
echo "[SWEEP:$sweep_name] Running: $cmd"
if ! $cmd; then
  echo "[ERROR] Sweep initialization failed: $sweep_name"
  exit 1
fi

# Extract run ID from the dist config generated by sweep_init.py
run_id=$(grep '^run:' "$DIST_CFG_PATH" | awk '{print $2}')
if [ -z "$run_id" ]; then
  echo "[ERROR] Failed to read run ID from $DIST_CFG_PATH"
  exit 1
fi

# Training phase - use train_job config
echo "[SWEEP:$sweep_name] Starting training phase..."

# Include hardware argument if it was provided
if [ -n "$hardware_arg" ]; then
  cmd="./devops/train.sh run=$run_id dist_cfg_path=$DIST_CFG_PATH data_dir=$DATA_DIR/sweep/$sweep_name/runs $hardware_arg"
else
  cmd="./devops/train.sh run=$run_id dist_cfg_path=$DIST_CFG_PATH data_dir=$DATA_DIR/sweep/$sweep_name/runs"
fi
echo "[SWEEP:$sweep_name] Running: $cmd"
if ! $cmd; then
  echo "[ERROR] Training failed for sweep: $sweep_name"
  exit 1
fi

# Evaluation phase
echo "[SWEEP:$sweep_name] Starting evaluation phase..."
cmd="./tools/sweep_eval.py dist_cfg_path=$DIST_CFG_PATH data_dir=$DATA_DIR/sweep/$sweep_name/runs $args"
echo "[SWEEP:$sweep_name] Running: $cmd"
if ! $cmd; then
  echo "[ERROR] Evaluation failed for sweep: $sweep_name"
  exit 1
fi

echo "[SUCCESS] Sweep rollout completed: $sweep_name"
