#!/usr/bin/env bash
set -e
./devops/skypilot/launch.py train --skip-git-check run=jacke.colortree_fast_jacke_2color_precise_1111_bptt16_easy_lstm_20250808_083922 trainer.env=/env/mettagrid/colortree_easy sim=colortree +user=jacke agent=fast trainer.bptt_horizon=16 +trainer.env_overrides.game.actions.color_tree.target_sequence=\[1\,1\,1\,1\] +trainer.env_overrides.game.actions.color_tree.trial_sequences=\[\[1\,1\,1\,1\]\] +trainer.env_overrides.game.actions.color_tree.num_trials=1 +trainer.env_overrides.game.actions.color_tree.reward_mode=precise 
./devops/skypilot/launch.py train --skip-git-check run=jacke.colortree_fast_jacke_2color_precise_1111_bptt64_easy_lstm_20250808_083922 trainer.env=/env/mettagrid/colortree_easy sim=colortree +user=jacke agent=fast trainer.bptt_horizon=64 +trainer.env_overrides.game.actions.color_tree.target_sequence=\[1\,1\,1\,1\] +trainer.env_overrides.game.actions.color_tree.trial_sequences=\[\[1\,1\,1\,1\]\] +trainer.env_overrides.game.actions.color_tree.num_trials=1 +trainer.env_overrides.game.actions.color_tree.reward_mode=precise 
./devops/skypilot/launch.py train --skip-git-check run=jacke.colortree_fast_jacke_2color_precise_1010_bptt16_easy_lstm_20250808_083922 trainer.env=/env/mettagrid/colortree_easy sim=colortree +user=jacke agent=fast trainer.bptt_horizon=16 +trainer.env_overrides.game.actions.color_tree.target_sequence=\[1\,0\,1\,0\] +trainer.env_overrides.game.actions.color_tree.trial_sequences=\[\[1\,0\,1\,0\]\] +trainer.env_overrides.game.actions.color_tree.num_trials=1 +trainer.env_overrides.game.actions.color_tree.reward_mode=precise 
./devops/skypilot/launch.py train --skip-git-check run=jacke.colortree_fast_jacke_2color_precise_1010_bptt64_easy_lstm_20250808_083922 trainer.env=/env/mettagrid/colortree_easy sim=colortree +user=jacke agent=fast trainer.bptt_horizon=64 +trainer.env_overrides.game.actions.color_tree.target_sequence=\[1\,0\,1\,0\] +trainer.env_overrides.game.actions.color_tree.trial_sequences=\[\[1\,0\,1\,0\]\] +trainer.env_overrides.game.actions.color_tree.num_trials=1 +trainer.env_overrides.game.actions.color_tree.reward_mode=precise 
./devops/skypilot/launch.py train --skip-git-check run=jacke.colortree_fast_jacke_2color_partial_1111_bptt16_easy_lstm_20250808_083922 trainer.env=/env/mettagrid/colortree_easy sim=colortree +user=jacke agent=fast trainer.bptt_horizon=16 +trainer.env_overrides.game.actions.color_tree.target_sequence=\[1\,1\,1\,1\] +trainer.env_overrides.game.actions.color_tree.trial_sequences=\[\[1\,1\,1\,1\]\] +trainer.env_overrides.game.actions.color_tree.num_trials=1 +trainer.env_overrides.game.actions.color_tree.reward_mode=partial 
./devops/skypilot/launch.py train --skip-git-check run=jacke.colortree_fast_jacke_2color_partial_1111_bptt64_easy_lstm_20250808_083922 trainer.env=/env/mettagrid/colortree_easy sim=colortree +user=jacke agent=fast trainer.bptt_horizon=64 +trainer.env_overrides.game.actions.color_tree.target_sequence=\[1\,1\,1\,1\] +trainer.env_overrides.game.actions.color_tree.trial_sequences=\[\[1\,1\,1\,1\]\] +trainer.env_overrides.game.actions.color_tree.num_trials=1 +trainer.env_overrides.game.actions.color_tree.reward_mode=partial 
./devops/skypilot/launch.py train --skip-git-check run=jacke.colortree_fast_jacke_2color_partial_1010_bptt16_easy_lstm_20250808_083922 trainer.env=/env/mettagrid/colortree_easy sim=colortree +user=jacke agent=fast trainer.bptt_horizon=16 +trainer.env_overrides.game.actions.color_tree.target_sequence=\[1\,0\,1\,0\] +trainer.env_overrides.game.actions.color_tree.trial_sequences=\[\[1\,0\,1\,0\]\] +trainer.env_overrides.game.actions.color_tree.num_trials=1 +trainer.env_overrides.game.actions.color_tree.reward_mode=partial 
./devops/skypilot/launch.py train --skip-git-check run=jacke.colortree_fast_jacke_2color_partial_1010_bptt64_easy_lstm_20250808_083922 trainer.env=/env/mettagrid/colortree_easy sim=colortree +user=jacke agent=fast trainer.bptt_horizon=64 +trainer.env_overrides.game.actions.color_tree.target_sequence=\[1\,0\,1\,0\] +trainer.env_overrides.game.actions.color_tree.trial_sequences=\[\[1\,0\,1\,0\]\] +trainer.env_overrides.game.actions.color_tree.num_trials=1 +trainer.env_overrides.game.actions.color_tree.reward_mode=partial 
./devops/skypilot/launch.py train --skip-git-check run=jacke.colortree_fast_jacke_2color_dense_1111_bptt16_easy_lstm_20250808_083922 trainer.env=/env/mettagrid/colortree_easy sim=colortree +user=jacke agent=fast trainer.bptt_horizon=16 +trainer.env_overrides.game.actions.color_tree.target_sequence=\[1\,1\,1\,1\] +trainer.env_overrides.game.actions.color_tree.trial_sequences=\[\[1\,1\,1\,1\]\] +trainer.env_overrides.game.actions.color_tree.num_trials=1 +trainer.env_overrides.game.actions.color_tree.reward_mode=dense 
./devops/skypilot/launch.py train --skip-git-check run=jacke.colortree_fast_jacke_2color_dense_1111_bptt64_easy_lstm_20250808_083922 trainer.env=/env/mettagrid/colortree_easy sim=colortree +user=jacke agent=fast trainer.bptt_horizon=64 +trainer.env_overrides.game.actions.color_tree.target_sequence=\[1\,1\,1\,1\] +trainer.env_overrides.game.actions.color_tree.trial_sequences=\[\[1\,1\,1\,1\]\] +trainer.env_overrides.game.actions.color_tree.num_trials=1 +trainer.env_overrides.game.actions.color_tree.reward_mode=dense 
./devops/skypilot/launch.py train --skip-git-check run=jacke.colortree_fast_jacke_2color_dense_1010_bptt16_easy_lstm_20250808_083922 trainer.env=/env/mettagrid/colortree_easy sim=colortree +user=jacke agent=fast trainer.bptt_horizon=16 +trainer.env_overrides.game.actions.color_tree.target_sequence=\[1\,0\,1\,0\] +trainer.env_overrides.game.actions.color_tree.trial_sequences=\[\[1\,0\,1\,0\]\] +trainer.env_overrides.game.actions.color_tree.num_trials=1 +trainer.env_overrides.game.actions.color_tree.reward_mode=dense 
./devops/skypilot/launch.py train --skip-git-check run=jacke.colortree_fast_jacke_2color_dense_1010_bptt64_easy_lstm_20250808_083922 trainer.env=/env/mettagrid/colortree_easy sim=colortree +user=jacke agent=fast trainer.bptt_horizon=64 +trainer.env_overrides.game.actions.color_tree.target_sequence=\[1\,0\,1\,0\] +trainer.env_overrides.game.actions.color_tree.trial_sequences=\[\[1\,0\,1\,0\]\] +trainer.env_overrides.game.actions.color_tree.num_trials=1 +trainer.env_overrides.game.actions.color_tree.reward_mode=dense 
./devops/skypilot/launch.py train --skip-git-check run=jacke.colortree_recurrent_jacke_2color_precise_1111_bptt16_easy_lstm_20250808_083922 trainer.env=/env/mettagrid/colortree_easy sim=colortree +user=jacke agent._target_=metta.agent.external.lstm_transformer.Recurrent trainer.bptt_horizon=16 +trainer.env_overrides.game.actions.color_tree.target_sequence=\[1\,1\,1\,1\] +trainer.env_overrides.game.actions.color_tree.trial_sequences=\[\[1\,1\,1\,1\]\] +trainer.env_overrides.game.actions.color_tree.num_trials=1 +trainer.env_overrides.game.actions.color_tree.reward_mode=precise 
./devops/skypilot/launch.py train --skip-git-check run=jacke.colortree_recurrent_jacke_2color_precise_1111_bptt64_easy_lstm_20250808_083922 trainer.env=/env/mettagrid/colortree_easy sim=colortree +user=jacke agent._target_=metta.agent.external.lstm_transformer.Recurrent trainer.bptt_horizon=64 +trainer.env_overrides.game.actions.color_tree.target_sequence=\[1\,1\,1\,1\] +trainer.env_overrides.game.actions.color_tree.trial_sequences=\[\[1\,1\,1\,1\]\] +trainer.env_overrides.game.actions.color_tree.num_trials=1 +trainer.env_overrides.game.actions.color_tree.reward_mode=precise 
./devops/skypilot/launch.py train --skip-git-check run=jacke.colortree_recurrent_jacke_2color_precise_1010_bptt16_easy_lstm_20250808_083922 trainer.env=/env/mettagrid/colortree_easy sim=colortree +user=jacke agent._target_=metta.agent.external.lstm_transformer.Recurrent trainer.bptt_horizon=16 +trainer.env_overrides.game.actions.color_tree.target_sequence=\[1\,0\,1\,0\] +trainer.env_overrides.game.actions.color_tree.trial_sequences=\[\[1\,0\,1\,0\]\] +trainer.env_overrides.game.actions.color_tree.num_trials=1 +trainer.env_overrides.game.actions.color_tree.reward_mode=precise 
./devops/skypilot/launch.py train --skip-git-check run=jacke.colortree_recurrent_jacke_2color_precise_1010_bptt64_easy_lstm_20250808_083922 trainer.env=/env/mettagrid/colortree_easy sim=colortree +user=jacke agent._target_=metta.agent.external.lstm_transformer.Recurrent trainer.bptt_horizon=64 +trainer.env_overrides.game.actions.color_tree.target_sequence=\[1\,0\,1\,0\] +trainer.env_overrides.game.actions.color_tree.trial_sequences=\[\[1\,0\,1\,0\]\] +trainer.env_overrides.game.actions.color_tree.num_trials=1 +trainer.env_overrides.game.actions.color_tree.reward_mode=precise 
./devops/skypilot/launch.py train --skip-git-check run=jacke.colortree_recurrent_jacke_2color_partial_1111_bptt16_easy_lstm_20250808_083922 trainer.env=/env/mettagrid/colortree_easy sim=colortree +user=jacke agent._target_=metta.agent.external.lstm_transformer.Recurrent trainer.bptt_horizon=16 +trainer.env_overrides.game.actions.color_tree.target_sequence=\[1\,1\,1\,1\] +trainer.env_overrides.game.actions.color_tree.trial_sequences=\[\[1\,1\,1\,1\]\] +trainer.env_overrides.game.actions.color_tree.num_trials=1 +trainer.env_overrides.game.actions.color_tree.reward_mode=partial 
./devops/skypilot/launch.py train --skip-git-check run=jacke.colortree_recurrent_jacke_2color_partial_1111_bptt64_easy_lstm_20250808_083922 trainer.env=/env/mettagrid/colortree_easy sim=colortree +user=jacke agent._target_=metta.agent.external.lstm_transformer.Recurrent trainer.bptt_horizon=64 +trainer.env_overrides.game.actions.color_tree.target_sequence=\[1\,1\,1\,1\] +trainer.env_overrides.game.actions.color_tree.trial_sequences=\[\[1\,1\,1\,1\]\] +trainer.env_overrides.game.actions.color_tree.num_trials=1 +trainer.env_overrides.game.actions.color_tree.reward_mode=partial 
./devops/skypilot/launch.py train --skip-git-check run=jacke.colortree_recurrent_jacke_2color_partial_1010_bptt16_easy_lstm_20250808_083922 trainer.env=/env/mettagrid/colortree_easy sim=colortree +user=jacke agent._target_=metta.agent.external.lstm_transformer.Recurrent trainer.bptt_horizon=16 +trainer.env_overrides.game.actions.color_tree.target_sequence=\[1\,0\,1\,0\] +trainer.env_overrides.game.actions.color_tree.trial_sequences=\[\[1\,0\,1\,0\]\] +trainer.env_overrides.game.actions.color_tree.num_trials=1 +trainer.env_overrides.game.actions.color_tree.reward_mode=partial 
./devops/skypilot/launch.py train --skip-git-check run=jacke.colortree_recurrent_jacke_2color_partial_1010_bptt64_easy_lstm_20250808_083922 trainer.env=/env/mettagrid/colortree_easy sim=colortree +user=jacke agent._target_=metta.agent.external.lstm_transformer.Recurrent trainer.bptt_horizon=64 +trainer.env_overrides.game.actions.color_tree.target_sequence=\[1\,0\,1\,0\] +trainer.env_overrides.game.actions.color_tree.trial_sequences=\[\[1\,0\,1\,0\]\] +trainer.env_overrides.game.actions.color_tree.num_trials=1 +trainer.env_overrides.game.actions.color_tree.reward_mode=partial 
./devops/skypilot/launch.py train --skip-git-check run=jacke.colortree_recurrent_jacke_2color_dense_1111_bptt16_easy_lstm_20250808_083922 trainer.env=/env/mettagrid/colortree_easy sim=colortree +user=jacke agent._target_=metta.agent.external.lstm_transformer.Recurrent trainer.bptt_horizon=16 +trainer.env_overrides.game.actions.color_tree.target_sequence=\[1\,1\,1\,1\] +trainer.env_overrides.game.actions.color_tree.trial_sequences=\[\[1\,1\,1\,1\]\] +trainer.env_overrides.game.actions.color_tree.num_trials=1 +trainer.env_overrides.game.actions.color_tree.reward_mode=dense 
./devops/skypilot/launch.py train --skip-git-check run=jacke.colortree_recurrent_jacke_2color_dense_1111_bptt64_easy_lstm_20250808_083922 trainer.env=/env/mettagrid/colortree_easy sim=colortree +user=jacke agent._target_=metta.agent.external.lstm_transformer.Recurrent trainer.bptt_horizon=64 +trainer.env_overrides.game.actions.color_tree.target_sequence=\[1\,1\,1\,1\] +trainer.env_overrides.game.actions.color_tree.trial_sequences=\[\[1\,1\,1\,1\]\] +trainer.env_overrides.game.actions.color_tree.num_trials=1 +trainer.env_overrides.game.actions.color_tree.reward_mode=dense 
./devops/skypilot/launch.py train --skip-git-check run=jacke.colortree_recurrent_jacke_2color_dense_1010_bptt16_easy_lstm_20250808_083922 trainer.env=/env/mettagrid/colortree_easy sim=colortree +user=jacke agent._target_=metta.agent.external.lstm_transformer.Recurrent trainer.bptt_horizon=16 +trainer.env_overrides.game.actions.color_tree.target_sequence=\[1\,0\,1\,0\] +trainer.env_overrides.game.actions.color_tree.trial_sequences=\[\[1\,0\,1\,0\]\] +trainer.env_overrides.game.actions.color_tree.num_trials=1 +trainer.env_overrides.game.actions.color_tree.reward_mode=dense 
./devops/skypilot/launch.py train --skip-git-check run=jacke.colortree_recurrent_jacke_2color_dense_1010_bptt64_easy_lstm_20250808_083922 trainer.env=/env/mettagrid/colortree_easy sim=colortree +user=jacke agent._target_=metta.agent.external.lstm_transformer.Recurrent trainer.bptt_horizon=64 +trainer.env_overrides.game.actions.color_tree.target_sequence=\[1\,0\,1\,0\] +trainer.env_overrides.game.actions.color_tree.trial_sequences=\[\[1\,0\,1\,0\]\] +trainer.env_overrides.game.actions.color_tree.num_trials=1 +trainer.env_overrides.game.actions.color_tree.reward_mode=dense 
