# Developer tools
tap "withgraphite/tap"
brew "amazon-efs-utils"
brew "awscli"
brew "bazelisk"
brew "clang-format"
brew "docker"
brew "googletest"
brew "google-benchmark"
cask "session-manager-plugin"
brew "withgraphite/tap/graphite"
brew "spacelift-io/spacelift/spacectl"

# Applications
cask "cursor"
cask "discord"
cask "miniconda"
