# Developer tools
tap "withgraphite/tap"
brew "awscli"
brew "bazelisk"
brew "docker"
brew "withgraphite/tap/graphite"
brew "clang-format"
brew "googletest"
brew "google-benchmark"

# Applications
cask "cursor"
cask "discord"
cask "miniconda"
