/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/tasks': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create Task */
    post: operations['create_task_tasks_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/latest': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Latest Assigned Task For Worker */
    get: operations['get_latest_assigned_task_for_worker_tasks_latest_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/available': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Available Tasks */
    get: operations['get_available_tasks_tasks_available_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/claim': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Claim Tasks */
    post: operations['claim_tasks_tasks_claim_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/claimed': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Claimed Tasks */
    get: operations['get_claimed_tasks_tasks_claimed_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/git-hashes': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Get Git Hashes For Workers */
    post: operations['get_git_hashes_for_workers_tasks_git_hashes_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/all': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get All Tasks */
    get: operations['get_all_tasks_tasks_all_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/paginated': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Tasks Paginated */
    get: operations['get_tasks_paginated_tasks_paginated_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/{task_id}/start': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Start Task */
    post: operations['start_task_tasks__task_id__start_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/{task_id}/finish': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Finish Task */
    post: operations['finish_task_tasks__task_id__finish_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/{task_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Task
     * @description Get a single task by ID with full details including attributes.
     */
    get: operations['get_task_tasks__task_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/{task_id}/attempts': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Task Attempts
     * @description Get all attempts for a specific task.
     */
    get: operations['get_task_attempts_tasks__task_id__attempts_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/{task_id}/logs/{log_type}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Task Logs
     * @description Stream log files from S3 for a specific task.
     *
     *     Args:
     *         task_id: The ID of the task
     *         log_type: Either "stdout" or "stderr" or "output"
     *
     *     Returns:
     *         StreamingResponse with the log file content as text/plain
     */
    get: operations['get_task_logs_tasks__task_id__logs__log_type__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sql/tables': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * List Tables
     * @description List all available tables in the database (excluding migrations).
     */
    get: operations['list_tables_sql_tables_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sql/tables/{table_name}/schema': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Table Schema
     * @description Get the schema for a specific table.
     */
    get: operations['get_table_schema_sql_tables__table_name__schema_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sql/query': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Execute Query
     * @description Execute a SQL query with a 20-second timeout.
     */
    post: operations['execute_query_sql_query_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sql/generate-query': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Generate Ai Query
     * @description Generate a SQL query from natural language description using Claude.
     */
    post: operations['generate_ai_query_sql_generate_query_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/stats/policies': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Policies */
    get: operations['get_policies_stats_policies_get']
    put?: never
    /** Upsert Policy */
    post: operations['upsert_policy_stats_policies_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/stats/policies/{policy_id_str}/versions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Create Policy Version */
    post: operations['create_policy_version_stats_policies__policy_id_str__versions_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/stats/policies/versions/{policy_version_id_str}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Policy Version */
    get: operations['get_policy_version_stats_policies_versions__policy_version_id_str__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/stats/policies/versions/{policy_version_id_str}/tags': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    /** Update Policy Version Tags Route */
    put: operations['update_policy_version_tags_route_stats_policies_versions__policy_version_id_str__tags_put']
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/stats/policies/submit': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Submit Policy */
    post: operations['submit_policy_stats_policies_submit_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/stats/policies/submit/presigned-url': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Get Submit Policy Presigned Url */
    post: operations['get_submit_policy_presigned_url_stats_policies_submit_presigned_url_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/stats/policies/submit/complete': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Complete Policy Submit */
    post: operations['complete_policy_submit_stats_policies_submit_complete_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/stats/episodes/bulk_upload/presigned-url': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Get Bulk Upload Presigned Url */
    post: operations['get_bulk_upload_presigned_url_stats_episodes_bulk_upload_presigned_url_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/stats/episodes/bulk_upload/complete': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Complete Bulk Upload */
    post: operations['complete_bulk_upload_stats_episodes_bulk_upload_complete_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/stats/policy-versions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Policy Versions */
    get: operations['get_policy_versions_stats_policy_versions_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/stats/policies/{policy_id}/versions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Versions For Policy */
    get: operations['get_versions_for_policy_stats_policies__policy_id__versions_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/stats/policies/my-versions': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get My Policy Versions */
    get: operations['get_my_policy_versions_stats_policies_my_versions_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/stats/episodes/query': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Query Episodes */
    post: operations['query_episodes_stats_episodes_query_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sweeps/{sweep_name}/create_sweep': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create Sweep
     * @description Initialize a new sweep or return existing sweep info (idempotent).
     */
    post: operations['create_sweep_sweeps__sweep_name__create_sweep_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sweeps/{sweep_name}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Sweep
     * @description Get sweep information by name.
     */
    get: operations['get_sweep_sweeps__sweep_name__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sweeps/{sweep_name}/runs/next': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Get Next Run Id
     * @description Get the next run ID for a sweep (atomic operation).
     */
    post: operations['get_next_run_id_sweeps__sweep_name__runs_next_post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/leaderboard/v2': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Leaderboard Policies V2 */
    get: operations['get_leaderboard_policies_v2_leaderboard_v2_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/leaderboard/v2/users/me': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Leaderboard Policies V2 For User */
    get: operations['get_leaderboard_policies_v2_for_user_leaderboard_v2_users_me_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/leaderboard/v2/policy/{policy_version_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Leaderboard Policies V2 For Policy */
    get: operations['get_leaderboard_policies_v2_for_policy_leaderboard_v2_policy__policy_version_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/leaderboard/v2/vor': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get Leaderboard With Vor
     * @description Get leaderboard entries with VOR computed for each policy (cached 60s).
     */
    get: operations['get_leaderboard_with_vor_leaderboard_v2_vor_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/whoami': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Whoami */
    get: operations['whoami_whoami_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** AIQueryRequest */
    AIQueryRequest: {
      /** Description */
      description: string
    }
    /** AIQueryResponse */
    AIQueryResponse: {
      /** Query */
      query: string
    }
    /** Body_submit_policy_stats_policies_submit_post */
    Body_submit_policy_stats_policies_submit_post: {
      /**
       * File
       * Format: binary
       */
      file: string
      /** Name */
      name: string
    }
    /**
     * BulkEpisodeUploadResponse
     * @description Response for bulk episode upload.
     */
    BulkEpisodeUploadResponse: {
      /** Episodes Created */
      episodes_created: number
      /** Duckdb S3 Uri */
      duckdb_s3_uri: string
    }
    /**
     * CompleteBulkUploadRequest
     * @description Request to complete a bulk upload.
     */
    CompleteBulkUploadRequest: {
      /**
       * Upload Id
       * Format: uuid
       */
      upload_id: string
    }
    /**
     * CompletePolicySubmitRequest
     * @description Request to complete a policy submission after uploading to S3.
     */
    CompletePolicySubmitRequest: {
      /**
       * Upload Id
       * Format: uuid
       */
      upload_id: string
      /** Name */
      name: string
    }
    /** EpisodeQueryRequest */
    EpisodeQueryRequest: {
      /** Primary Policy Version Ids */
      primary_policy_version_ids?: string[] | null
      /** Episode Ids */
      episode_ids?: string[] | null
      /** Tag Filters */
      tag_filters?: {
        [key: string]: string[] | null
      } | null
      /**
       * Limit
       * @default 200
       */
      limit: number | null
      /**
       * Offset
       * @default 0
       */
      offset: number
    }
    /** EpisodeQueryResponse */
    EpisodeQueryResponse: {
      /** Episodes */
      episodes: components['schemas']['EpisodeWithTags'][]
    }
    /** EpisodeReplay */
    EpisodeReplay: {
      /**
       * Episode Id
       * Format: uuid
       */
      episode_id: string
      /** Replay Url */
      replay_url: string
    }
    /** EpisodeWithTags */
    EpisodeWithTags: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Primary Pv Id */
      primary_pv_id: string | null
      /** Replay Url */
      replay_url: string | null
      /** Thumbnail Url */
      thumbnail_url: string | null
      /** Attributes */
      attributes?: {
        [key: string]: unknown
      }
      /** Eval Task Id */
      eval_task_id: string | null
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Tags */
      tags?: {
        [key: string]: string
      }
      /** Avg Rewards */
      avg_rewards?: {
        [key: string]: number
      }
    }
    /**
     * EvalTaskRow
     * @description Row model that matches the eval_tasks table with latest attempt data.
     */
    EvalTaskRow: {
      /** Id */
      id: number
      /** Command */
      command: string
      /** Data Uri */
      data_uri: string | null
      /** Git Hash */
      git_hash: string | null
      /** Attributes */
      attributes: {
        [key: string]: unknown
      }
      /** User Id */
      user_id: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Is Finished */
      is_finished: boolean
      /** Latest Attempt Id */
      latest_attempt_id: number | null
      /**
       * Attempt Number
       * @default 0
       */
      attempt_number: number | null
      /**
       * Status
       * @default unprocessed
       * @enum {string}
       */
      status: 'unprocessed' | 'running' | 'canceled' | 'done' | 'error' | 'system_error'
      /** Status Details */
      status_details?: {
        [key: string]: unknown
      } | null
      /** Assigned At */
      assigned_at?: string | null
      /** Assignee */
      assignee?: string | null
      /** Started At */
      started_at?: string | null
      /** Finished At */
      finished_at?: string | null
      /** Output Log Path */
      output_log_path?: string | null
    }
    /** GitHashesRequest */
    GitHashesRequest: {
      /** Assignees */
      assignees: string[]
    }
    /** GitHashesResponse */
    GitHashesResponse: {
      /** Git Hashes */
      git_hashes: {
        [key: string]: string[]
      }
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** LeaderboardPoliciesResponse */
    LeaderboardPoliciesResponse: {
      /** Entries */
      entries: components['schemas']['LeaderboardPolicyEntry'][]
    }
    /** LeaderboardPolicyEntry */
    LeaderboardPolicyEntry: {
      policy_version: components['schemas']['PublicPolicyVersionRow']
      /** Scores */
      scores: {
        [key: string]: number
      }
      /** Avg Score */
      avg_score?: number | null
      /** Overall Vor */
      overall_vor?: number | null
      /** Replays */
      replays?: {
        [key: string]: components['schemas']['EpisodeReplay'][]
      }
      /** Score Episode Ids */
      score_episode_ids?: {
        [key: string]: string | null
      }
    }
    /** MyPolicyVersionsResponse */
    MyPolicyVersionsResponse: {
      /** Entries */
      entries: components['schemas']['PublicPolicyVersionRow'][]
    }
    /** PaginatedTasksResponse */
    PaginatedTasksResponse: {
      /** Tasks */
      tasks: components['schemas']['EvalTaskRow'][]
      /** Total Count */
      total_count: number
      /** Page */
      page: number
      /** Page Size */
      page_size: number
      /** Total Pages */
      total_pages: number
    }
    /** PoliciesResponse */
    PoliciesResponse: {
      /** Entries */
      entries: components['schemas']['PolicyRow'][]
      /** Total Count */
      total_count: number
    }
    /** PolicyCreate */
    PolicyCreate: {
      /** Name */
      name: string
      /** Attributes */
      attributes?: {
        [key: string]: unknown
      }
      /**
       * Is System Policy
       * @default false
       */
      is_system_policy: boolean
    }
    /** PolicyRow */
    PolicyRow: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Name */
      name: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** User Id */
      user_id: string
      /** Attributes */
      attributes: {
        [key: string]: unknown
      }
      /** Version Count */
      version_count: number
    }
    /** PolicyVersionCreate */
    PolicyVersionCreate: {
      /** Policy Spec */
      policy_spec?: {
        [key: string]: unknown
      }
      /** Git Hash */
      git_hash?: string | null
      /** Attributes */
      attributes?: {
        [key: string]: unknown
      }
      /** S3 Path */
      s3_path?: string | null
    }
    /** PolicyVersionWithName */
    PolicyVersionWithName: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /** Internal Id */
      internal_id: number
      /**
       * Policy Id
       * Format: uuid
       */
      policy_id: string
      /** Version */
      version: number
      /** S3 Path */
      s3_path: string | null
      /** Git Hash */
      git_hash: string | null
      /** Policy Spec */
      policy_spec: {
        [key: string]: unknown
      }
      /** Attributes */
      attributes: {
        [key: string]: unknown
      }
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /** Name */
      name: string
    }
    /** PolicyVersionsResponse */
    PolicyVersionsResponse: {
      /** Entries */
      entries: components['schemas']['PublicPolicyVersionRow'][]
      /** Total Count */
      total_count: number
    }
    /**
     * PresignedUploadUrlResponse
     * @description Response containing presigned URL for direct S3 upload.
     */
    PresignedUploadUrlResponse: {
      /** Upload Url */
      upload_url: string
      /** S3 Key */
      s3_key: string
      /**
       * Upload Id
       * Format: uuid
       */
      upload_id: string
    }
    /** PublicPolicyVersionRow */
    PublicPolicyVersionRow: {
      /**
       * Id
       * Format: uuid
       */
      id: string
      /**
       * Policy Id
       * Format: uuid
       */
      policy_id: string
      /**
       * Created At
       * Format: date-time
       */
      created_at: string
      /**
       * Policy Created At
       * Format: date-time
       */
      policy_created_at: string
      /** User Id */
      user_id: string
      /** Name */
      name: string
      /** Version */
      version: number
      /** Tags */
      tags?: {
        [key: string]: string
      }
      /** Version Count */
      version_count?: number | null
    }
    /** RunIdResponse */
    RunIdResponse: {
      /** Run Id */
      run_id: string
    }
    /** SQLQueryRequest */
    SQLQueryRequest: {
      /** Query */
      query: string
    }
    /** SQLQueryResponse */
    SQLQueryResponse: {
      /** Columns */
      columns: string[]
      /** Rows */
      rows: unknown[][]
      /** Row Count */
      row_count: number
    }
    /** SweepCreateRequest */
    SweepCreateRequest: {
      /** Project */
      project: string
      /** Entity */
      entity: string
      /** Wandb Sweep Id */
      wandb_sweep_id: string
    }
    /** SweepCreateResponse */
    SweepCreateResponse: {
      /** Created */
      created: boolean
      /**
       * Sweep Id
       * Format: uuid
       */
      sweep_id: string
    }
    /** SweepInfo */
    SweepInfo: {
      /** Exists */
      exists: boolean
      /** Wandb Sweep Id */
      wandb_sweep_id: string
    }
    /** TableInfo */
    TableInfo: {
      /** Table Name */
      table_name: string
      /** Column Count */
      column_count: number
      /** Row Count */
      row_count: number
    }
    /** TableSchema */
    TableSchema: {
      /** Table Name */
      table_name: string
      /** Columns */
      columns: {
        [key: string]: unknown
      }[]
    }
    /**
     * TaskAttemptRow
     * @description Row model for task_attempts table.
     */
    TaskAttemptRow: {
      /** Id */
      id: number
      /** Task Id */
      task_id: number
      /** Attempt Number */
      attempt_number: number
      /** Assigned At */
      assigned_at: string | null
      /** Assignee */
      assignee: string | null
      /** Started At */
      started_at: string | null
      /** Finished At */
      finished_at: string | null
      /** Output Log Path */
      output_log_path: string | null
      /**
       * Status
       * @enum {string}
       */
      status: 'unprocessed' | 'running' | 'canceled' | 'done' | 'error' | 'system_error'
      /** Status Details */
      status_details: {
        [key: string]: unknown
      } | null
    }
    /** TaskAttemptsResponse */
    TaskAttemptsResponse: {
      /** Attempts */
      attempts: components['schemas']['TaskAttemptRow'][]
    }
    /** TaskClaimRequest */
    TaskClaimRequest: {
      /** Tasks */
      tasks: number[]
      /** Assignee */
      assignee: string
    }
    /** TaskClaimResponse */
    TaskClaimResponse: {
      /** Claimed */
      claimed: number[]
    }
    /** TaskCreateRequest */
    TaskCreateRequest: {
      /** Command */
      command: string
      /** Git Hash */
      git_hash?: string | null
      /** Data File */
      data_file?: {
        [key: string]: unknown
      } | null
      /** Attributes */
      attributes?: {
        [key: string]: unknown
      }
    }
    /** TaskFinishRequest */
    TaskFinishRequest: {
      /** Task Id */
      task_id: number
      /**
       * Status
       * @enum {string}
       */
      status: 'done' | 'error' | 'canceled' | 'system_error'
      /** Log Path */
      log_path?: string | null
      /** Status Details */
      status_details?: {
        [key: string]: unknown
      }
    }
    /** TaskIdResponse */
    TaskIdResponse: {
      /** Task Id */
      task_id: number
    }
    /** TasksResponse */
    TasksResponse: {
      /** Tasks */
      tasks: components['schemas']['EvalTaskRow'][]
    }
    /** UUIDResponse */
    UUIDResponse: {
      /**
       * Id
       * Format: uuid
       */
      id: string
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
    /** WhoAmIResponse */
    WhoAmIResponse: {
      /** User Email */
      user_email: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  create_task_tasks_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TaskCreateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EvalTaskRow']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_latest_assigned_task_for_worker_tasks_latest_get: {
    parameters: {
      query: {
        assignee: string
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EvalTaskRow']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_available_tasks_tasks_available_get: {
    parameters: {
      query?: {
        limit?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TasksResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  claim_tasks_tasks_claim_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TaskClaimRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TaskClaimResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_claimed_tasks_tasks_claimed_get: {
    parameters: {
      query?: {
        assignee?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TasksResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_git_hashes_for_workers_tasks_git_hashes_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['GitHashesRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['GitHashesResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_all_tasks_tasks_all_get: {
    parameters: {
      query?: {
        limit?: number
        statuses?: ('unprocessed' | 'running' | 'canceled' | 'done' | 'error' | 'system_error')[] | null
        git_hash?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TasksResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_tasks_paginated_tasks_paginated_get: {
    parameters: {
      query?: {
        page?: number
        page_size?: number
        status?: string | null
        assignee?: string | null
        user_id?: string | null
        command?: string | null
        created_at?: string | null
        assigned_at?: string | null
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PaginatedTasksResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  start_task_tasks__task_id__start_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        task_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TaskIdResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  finish_task_tasks__task_id__finish_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        task_id: number
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['TaskFinishRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TaskIdResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_task_tasks__task_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        task_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EvalTaskRow']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_task_attempts_tasks__task_id__attempts_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        task_id: number
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TaskAttemptsResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_task_logs_tasks__task_id__logs__log_type__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        task_id: number
        log_type: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  list_tables_sql_tables_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TableInfo'][]
        }
      }
    }
  }
  get_table_schema_sql_tables__table_name__schema_get: {
    parameters: {
      query?: never
      header?: never
      path: {
        table_name: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TableSchema']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  execute_query_sql_query_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SQLQueryRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SQLQueryResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  generate_ai_query_sql_generate_query_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['AIQueryRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['AIQueryResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_policies_stats_policies_get: {
    parameters: {
      query?: {
        name_exact?: string | null
        name_fuzzy?: string | null
        limit?: number
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PoliciesResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  upsert_policy_stats_policies_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PolicyCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UUIDResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_policy_version_stats_policies__policy_id_str__versions_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        policy_id_str: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['PolicyVersionCreate']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UUIDResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_policy_version_stats_policies_versions__policy_version_id_str__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        policy_version_id_str: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PolicyVersionWithName']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  update_policy_version_tags_route_stats_policies_versions__policy_version_id_str__tags_put: {
    parameters: {
      query?: never
      header?: never
      path: {
        policy_version_id_str: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': {
          [key: string]: string
        }
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UUIDResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  submit_policy_stats_policies_submit_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_submit_policy_stats_policies_submit_post']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UUIDResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_submit_policy_presigned_url_stats_policies_submit_presigned_url_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PresignedUploadUrlResponse']
        }
      }
    }
  }
  complete_policy_submit_stats_policies_submit_complete_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CompletePolicySubmitRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['UUIDResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_bulk_upload_presigned_url_stats_episodes_bulk_upload_presigned_url_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PresignedUploadUrlResponse']
        }
      }
    }
  }
  complete_bulk_upload_stats_episodes_bulk_upload_complete_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['CompleteBulkUploadRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['BulkEpisodeUploadResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_policy_versions_stats_policy_versions_get: {
    parameters: {
      query?: {
        name_exact?: string | null
        name_fuzzy?: string | null
        version?: number | null
        policy_version_ids?: string[] | null
        limit?: number
        offset?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PolicyVersionsResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_versions_for_policy_stats_policies__policy_id__versions_get: {
    parameters: {
      query?: {
        limit?: number
        offset?: number
      }
      header?: never
      path: {
        policy_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['PolicyVersionsResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_my_policy_versions_stats_policies_my_versions_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['MyPolicyVersionsResponse']
        }
      }
    }
  }
  query_episodes_stats_episodes_query_post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['EpisodeQueryRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['EpisodeQueryResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  create_sweep_sweeps__sweep_name__create_sweep_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        sweep_name: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['SweepCreateRequest']
      }
    }
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SweepCreateResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_sweep_sweeps__sweep_name__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        sweep_name: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['SweepInfo']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_next_run_id_sweeps__sweep_name__runs_next_post: {
    parameters: {
      query?: never
      header?: never
      path: {
        sweep_name: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['RunIdResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_leaderboard_policies_v2_leaderboard_v2_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LeaderboardPoliciesResponse']
        }
      }
    }
  }
  get_leaderboard_policies_v2_for_user_leaderboard_v2_users_me_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LeaderboardPoliciesResponse']
        }
      }
    }
  }
  get_leaderboard_policies_v2_for_policy_leaderboard_v2_policy__policy_version_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        policy_version_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LeaderboardPoliciesResponse']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_leaderboard_with_vor_leaderboard_v2_vor_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['LeaderboardPoliciesResponse']
        }
      }
    }
  }
  whoami_whoami_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['WhoAmIResponse']
        }
      }
    }
  }
}
