export interface Affiliation {
    id: string;
    name: string;
    label: string;
    logo: string;
    initials: string;
    location: string;
    type: string;
    memberCount: number;
    papers: number;
    citations: number;
    tags: string[];
    lastActive: string;
    website: string;
    isFavorite: boolean;
    isAdmin: boolean;
}

export const mockAffiliations: Affiliation[] = [
    {
        id: 'stanford-ai-lab',
        name: 'Stanford University',
        label: 'Stanford AI Lab',
        logo: '',
        initials: 'SAIL',
        location: 'Stanford, USA',
        type: 'University',
        memberCount: 42,
        papers: 320,
        citations: 15400,
        tags: ['AI', 'Robotics', 'NLP', 'Vision', 'Theory'],
        lastActive: '2024-06-01',
        website: 'https://ai.stanford.edu',
        isFavorite: true,
        isAdmin: false
    },
    {
        id: 'deepmind',
        name: 'DeepMind',
        label: 'DeepMind',
        logo: '',
        initials: 'DM',
        location: 'London, UK',
        type: 'Corporate Lab',
        memberCount: 87,
        papers: 510,
        citations: 32000,
        tags: ['Reinforcement Learning', 'Neuroscience', 'AI'],
        lastActive: '2024-05-28',
        website: 'https://deepmind.com',
        isFavorite: false,
        isAdmin: true
    },
    {
        id: 'berkeley-ai',
        name: 'UC Berkeley',
        label: 'Berkeley AI Research',
        logo: '',
        initials: 'BAIR',
        location: 'Berkeley, USA',
        type: 'University',
        memberCount: 35,
        papers: 210,
        citations: 9800,
        tags: ['Robotics', 'Vision', 'ML Theory'],
        lastActive: '2024-05-15',
        website: 'https://bair.berkeley.edu',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'mit-csail',
        name: 'MIT',
        label: 'MIT CSAIL',
        logo: '',
        initials: 'CSAIL',
        location: 'Cambridge, USA',
        type: 'University',
        memberCount: 120,
        papers: 890,
        citations: 45000,
        tags: ['AI', 'Systems', 'Theory', 'Robotics'],
        lastActive: '2024-06-02',
        website: 'https://www.csail.mit.edu',
        isFavorite: true,
        isAdmin: false
    },
    {
        id: 'openai',
        name: 'OpenAI',
        label: 'OpenAI',
        logo: '',
        initials: 'OA',
        location: 'San Francisco, USA',
        type: 'Corporate Lab',
        memberCount: 150,
        papers: 45,
        citations: 25000,
        tags: ['Large Language Models', 'AI Safety', 'Generative AI'],
        lastActive: '2024-05-30',
        website: 'https://openai.com',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'cmu-ml',
        name: 'Carnegie Mellon University',
        label: 'CMU Machine Learning',
        logo: '',
        initials: 'CMU',
        location: 'Pittsburgh, USA',
        type: 'University',
        memberCount: 28,
        papers: 180,
        citations: 12000,
        tags: ['Machine Learning', 'Robotics', 'NLP'],
        lastActive: '2024-05-20',
        website: 'https://www.ml.cmu.edu',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'google-brain',
        name: 'Google',
        label: 'Google Brain',
        logo: '',
        initials: 'GB',
        location: 'Mountain View, USA',
        type: 'Corporate Lab',
        memberCount: 200,
        papers: 350,
        citations: 28000,
        tags: ['Deep Learning', 'TensorFlow', 'AI Research'],
        lastActive: '2024-05-25',
        website: 'https://research.google/teams/brain',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'oxford-ai',
        name: 'University of Oxford',
        label: 'Oxford AI',
        logo: '',
        initials: 'OX',
        location: 'Oxford, UK',
        type: 'University',
        memberCount: 45,
        papers: 280,
        citations: 18000,
        tags: ['AI', 'Computer Vision', 'Robotics'],
        lastActive: '2024-05-18',
        website: 'https://www.robots.ox.ac.uk',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'facebook-ai',
        name: 'Meta',
        label: 'Facebook AI Research',
        logo: '',
        initials: 'FAIR',
        location: 'Menlo Park, USA',
        type: 'Corporate Lab',
        memberCount: 180,
        papers: 420,
        citations: 22000,
        tags: ['Computer Vision', 'NLP', 'AI'],
        lastActive: '2024-05-22',
        website: 'https://ai.facebook.com',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'toronto-ai',
        name: 'University of Toronto',
        label: 'Toronto AI',
        logo: '',
        initials: 'UoT',
        location: 'Toronto, Canada',
        type: 'University',
        memberCount: 32,
        papers: 195,
        citations: 11000,
        tags: ['Deep Learning', 'AI', 'Theory'],
        lastActive: '2024-05-12',
        website: 'https://www.cs.toronto.edu',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'microsoft-research',
        name: 'Microsoft',
        label: 'Microsoft Research',
        logo: '',
        initials: 'MSR',
        location: 'Redmond, USA',
        type: 'Corporate Lab',
        memberCount: 160,
        papers: 380,
        citations: 19000,
        tags: ['AI', 'Systems', 'Theory'],
        lastActive: '2024-05-28',
        website: 'https://www.microsoft.com/en-us/research',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'eth-zurich',
        name: 'ETH Zurich',
        label: 'ETH AI',
        logo: '',
        initials: 'ETH',
        location: 'Zurich, Switzerland',
        type: 'University',
        memberCount: 38,
        papers: 220,
        citations: 13500,
        tags: ['Robotics', 'Computer Vision', 'AI'],
        lastActive: '2024-05-15',
        website: 'https://ai.ethz.ch',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'nvidia-research',
        name: 'NVIDIA',
        label: 'NVIDIA Research',
        logo: '',
        initials: 'NV',
        location: 'Santa Clara, USA',
        type: 'Corporate Lab',
        memberCount: 90,
        papers: 120,
        citations: 8000,
        tags: ['Computer Graphics', 'AI', 'Hardware'],
        lastActive: '2024-05-20',
        website: 'https://www.nvidia.com/en-us/research',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'caltech-ai',
        name: 'Caltech',
        label: 'Caltech AI',
        logo: '',
        initials: 'CIT',
        location: 'Pasadena, USA',
        type: 'University',
        memberCount: 25,
        papers: 150,
        citations: 9500,
        tags: ['AI', 'Robotics', 'Theory'],
        lastActive: '2024-05-10',
        website: 'https://www.caltech.edu',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'amazon-ai',
        name: 'Amazon',
        label: 'Amazon AI',
        logo: '',
        initials: 'AWS',
        location: 'Seattle, USA',
        type: 'Corporate Lab',
        memberCount: 110,
        papers: 180,
        citations: 12000,
        tags: ['Machine Learning', 'Cloud AI', 'NLP'],
        lastActive: '2024-05-25',
        website: 'https://aws.amazon.com/machine-learning',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'ucl-ai',
        name: 'University College London',
        label: 'UCL AI',
        logo: '',
        initials: 'UCL',
        location: 'London, UK',
        type: 'University',
        memberCount: 40,
        papers: 260,
        citations: 16000,
        tags: ['AI', 'Neuroscience', 'Computer Vision'],
        lastActive: '2024-05-18',
        website: 'https://www.ucl.ac.uk/ai',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'apple-ai',
        name: 'Apple',
        label: 'Apple AI/ML',
        logo: '',
        initials: 'AAPL',
        location: 'Cupertino, USA',
        type: 'Corporate Lab',
        memberCount: 80,
        papers: 60,
        citations: 5000,
        tags: ['Machine Learning', 'Computer Vision', 'Privacy'],
        lastActive: '2024-05-22',
        website: 'https://machinelearning.apple.com',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'epfl-ai',
        name: 'EPFL',
        label: 'EPFL AI',
        logo: '',
        initials: 'EPFL',
        location: 'Lausanne, Switzerland',
        type: 'University',
        memberCount: 35,
        papers: 200,
        citations: 12500,
        tags: ['AI', 'Robotics', 'Computer Vision'],
        lastActive: '2024-05-14',
        website: 'https://www.epfl.ch/labs/ai',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'ibm-research',
        name: 'IBM',
        label: 'IBM Research',
        logo: '',
        initials: 'IBM',
        location: 'Yorktown Heights, USA',
        type: 'Corporate Lab',
        memberCount: 120,
        papers: 300,
        citations: 18000,
        tags: ['AI', 'Quantum Computing', 'Systems'],
        lastActive: '2024-05-16',
        website: 'https://www.research.ibm.com',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'nyu-ai',
        name: 'New York University',
        label: 'NYU AI',
        logo: '',
        initials: 'NYU',
        location: 'New York, USA',
        type: 'University',
        memberCount: 30,
        papers: 175,
        citations: 11000,
        tags: ['AI', 'Computer Vision', 'NLP'],
        lastActive: '2024-05-12',
        website: 'https://ai.nyu.edu',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'salesforce-ai',
        name: 'Salesforce',
        label: 'Salesforce AI',
        logo: '',
        initials: 'SF',
        location: 'San Francisco, USA',
        type: 'Corporate Lab',
        memberCount: 70,
        papers: 90,
        citations: 6000,
        tags: ['NLP', 'Machine Learning', 'Enterprise AI'],
        lastActive: '2024-05-20',
        website: 'https://www.salesforce.com/products/einstein',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'cambridge-ai',
        name: 'University of Cambridge',
        label: 'Cambridge AI',
        logo: '',
        initials: 'CAM',
        location: 'Cambridge, UK',
        type: 'University',
        memberCount: 42,
        papers: 240,
        citations: 15000,
        tags: ['AI', 'Computer Vision', 'Robotics'],
        lastActive: '2024-05-17',
        website: 'https://www.cam.ac.uk/research/ai',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'netflix-ai',
        name: 'Netflix',
        label: 'Netflix AI',
        logo: '',
        initials: 'NFLX',
        location: 'Los Gatos, USA',
        type: 'Corporate Lab',
        memberCount: 45,
        papers: 30,
        citations: 2000,
        tags: ['Recommendation Systems', 'Machine Learning'],
        lastActive: '2024-05-15',
        website: 'https://research.netflix.com',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'imperial-ai',
        name: 'Imperial College London',
        label: 'Imperial AI',
        logo: '',
        initials: 'ICL',
        location: 'London, UK',
        type: 'University',
        memberCount: 38,
        papers: 210,
        citations: 13000,
        tags: ['AI', 'Robotics', 'Computer Vision'],
        lastActive: '2024-05-19',
        website: 'https://www.imperial.ac.uk/ai',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'spotify-ai',
        name: 'Spotify',
        label: 'Spotify AI',
        logo: '',
        initials: 'SPOT',
        location: 'Stockholm, Sweden',
        type: 'Corporate Lab',
        memberCount: 55,
        papers: 25,
        citations: 1500,
        tags: ['Audio AI', 'Recommendation Systems'],
        lastActive: '2024-05-13',
        website: 'https://research.atspotify.com',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'edinburgh-ai',
        name: 'University of Edinburgh',
        label: 'Edinburgh AI',
        logo: '',
        initials: 'UoE',
        location: 'Edinburgh, UK',
        type: 'University',
        memberCount: 36,
        papers: 225,
        citations: 14000,
        tags: ['NLP', 'AI', 'Machine Learning'],
        lastActive: '2024-05-16',
        website: 'https://www.ed.ac.uk/informatics',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'uber-ai',
        name: 'Uber',
        label: 'Uber AI',
        logo: '',
        initials: 'UBER',
        location: 'San Francisco, USA',
        type: 'Corporate Lab',
        memberCount: 65,
        papers: 40,
        citations: 3000,
        tags: ['Autonomous Vehicles', 'Machine Learning'],
        lastActive: '2024-05-18',
        website: 'https://www.uber.com/us/en/uberai',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'manchester-ai',
        name: 'University of Manchester',
        label: 'Manchester AI',
        logo: '',
        initials: 'UoM',
        location: 'Manchester, UK',
        type: 'University',
        memberCount: 28,
        papers: 160,
        citations: 9500,
        tags: ['AI', 'Computer Vision', 'Robotics'],
        lastActive: '2024-05-11',
        website: 'https://www.manchester.ac.uk/ai',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'airbnb-ai',
        name: 'Airbnb',
        label: 'Airbnb AI',
        logo: '',
        initials: 'ABNB',
        location: 'San Francisco, USA',
        type: 'Corporate Lab',
        memberCount: 40,
        papers: 20,
        citations: 1200,
        tags: ['Recommendation Systems', 'Computer Vision'],
        lastActive: '2024-05-14',
        website: 'https://airbnb.design',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'bristol-ai',
        name: 'University of Bristol',
        label: 'Bristol AI',
        logo: '',
        initials: 'UoB',
        location: 'Bristol, UK',
        type: 'University',
        memberCount: 24,
        papers: 140,
        citations: 8500,
        tags: ['AI', 'Robotics', 'Computer Vision'],
        lastActive: '2024-05-10',
        website: 'https://www.bristol.ac.uk/ai',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'linkedin-ai',
        name: 'LinkedIn',
        label: 'LinkedIn AI',
        logo: '',
        initials: 'LI',
        location: 'Sunnyvale, USA',
        type: 'Corporate Lab',
        memberCount: 50,
        papers: 35,
        citations: 2500,
        tags: ['Recommendation Systems', 'NLP'],
        lastActive: '2024-05-17',
        website: 'https://engineering.linkedin.com',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'warwick-ai',
        name: 'University of Warwick',
        label: 'Warwick AI',
        logo: '',
        initials: 'UoW',
        location: 'Coventry, UK',
        type: 'University',
        memberCount: 22,
        papers: 125,
        citations: 7500,
        tags: ['AI', 'Machine Learning', 'Computer Vision'],
        lastActive: '2024-05-12',
        website: 'https://warwick.ac.uk/ai',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'twitter-ai',
        name: 'Twitter',
        label: 'Twitter AI',
        logo: '',
        initials: 'TWTR',
        location: 'San Francisco, USA',
        type: 'Corporate Lab',
        memberCount: 60,
        papers: 30,
        citations: 2000,
        tags: ['NLP', 'Recommendation Systems'],
        lastActive: '2024-05-15',
        website: 'https://blog.twitter.com/engineering',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'sheffield-ai',
        name: 'University of Sheffield',
        label: 'Sheffield AI',
        logo: '',
        initials: 'UoS',
        location: 'Sheffield, UK',
        type: 'University',
        memberCount: 26,
        papers: 135,
        citations: 8000,
        tags: ['NLP', 'AI', 'Machine Learning'],
        lastActive: '2024-05-13',
        website: 'https://www.sheffield.ac.uk/ai',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'snap-ai',
        name: 'Snap Inc.',
        label: 'Snap AI',
        logo: '',
        initials: 'SNAP',
        location: 'Santa Monica, USA',
        type: 'Corporate Lab',
        memberCount: 45,
        papers: 25,
        citations: 1500,
        tags: ['Computer Vision', 'AR/VR'],
        lastActive: '2024-05-16',
        website: 'https://research.snap.com',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'leeds-ai',
        name: 'University of Leeds',
        label: 'Leeds AI',
        logo: '',
        initials: 'UoL',
        location: 'Leeds, UK',
        type: 'University',
        memberCount: 20,
        papers: 110,
        citations: 6500,
        tags: ['AI', 'Computer Vision', 'Robotics'],
        lastActive: '2024-05-11',
        website: 'https://www.leeds.ac.uk/ai',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'pinterest-ai',
        name: 'Pinterest',
        label: 'Pinterest AI',
        logo: '',
        initials: 'PINS',
        location: 'San Francisco, USA',
        type: 'Corporate Lab',
        memberCount: 40,
        papers: 20,
        citations: 1200,
        tags: ['Computer Vision', 'Recommendation Systems'],
        lastActive: '2024-05-14',
        website: 'https://medium.com/pinterest-engineering',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'liverpool-ai',
        name: 'University of Liverpool',
        label: 'Liverpool AI',
        logo: '',
        initials: 'UoL',
        location: 'Liverpool, UK',
        type: 'University',
        memberCount: 18,
        papers: 95,
        citations: 5500,
        tags: ['AI', 'Machine Learning', 'Computer Vision'],
        lastActive: '2024-05-10',
        website: 'https://www.liverpool.ac.uk/ai',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'yelp-ai',
        name: 'Yelp',
        label: 'Yelp AI',
        logo: '',
        initials: 'YELP',
        location: 'San Francisco, USA',
        type: 'Corporate Lab',
        memberCount: 35,
        papers: 15,
        citations: 800,
        tags: ['NLP', 'Recommendation Systems'],
        lastActive: '2024-05-13',
        website: 'https://engineeringblog.yelp.com',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'nottingham-ai',
        name: 'University of Nottingham',
        label: 'Nottingham AI',
        logo: '',
        initials: 'UoN',
        location: 'Nottingham, UK',
        type: 'University',
        memberCount: 19,
        papers: 100,
        citations: 6000,
        tags: ['AI', 'Computer Vision', 'Robotics'],
        lastActive: '2024-05-12',
        website: 'https://www.nottingham.ac.uk/ai',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'reddit-ai',
        name: 'Reddit',
        label: 'Reddit AI',
        logo: '',
        initials: 'RDDT',
        location: 'San Francisco, USA',
        type: 'Corporate Lab',
        memberCount: 30,
        papers: 12,
        citations: 600,
        tags: ['NLP', 'Recommendation Systems'],
        lastActive: '2024-05-15',
        website: 'https://redditblog.com',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'birmingham-ai',
        name: 'University of Birmingham',
        label: 'Birmingham AI',
        logo: '',
        initials: 'UoB',
        location: 'Birmingham, UK',
        type: 'University',
        memberCount: 17,
        papers: 85,
        citations: 5000,
        tags: ['AI', 'Machine Learning', 'Computer Vision'],
        lastActive: '2024-05-11',
        website: 'https://www.birmingham.ac.uk/ai',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'quora-ai',
        name: 'Quora',
        label: 'Quora AI',
        logo: '',
        initials: 'Q',
        location: 'Mountain View, USA',
        type: 'Corporate Lab',
        memberCount: 25,
        papers: 10,
        citations: 400,
        tags: ['NLP', 'Question Answering'],
        lastActive: '2024-05-14',
        website: 'https://quoraengineering.quora.com',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'cardiff-ai',
        name: 'Cardiff University',
        label: 'Cardiff AI',
        logo: '',
        initials: 'CU',
        location: 'Cardiff, UK',
        type: 'University',
        memberCount: 16,
        papers: 80,
        citations: 4500,
        tags: ['AI', 'Computer Vision', 'Robotics'],
        lastActive: '2024-05-10',
        website: 'https://www.cardiff.ac.uk/ai',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'stackoverflow-ai',
        name: 'Stack Overflow',
        label: 'Stack Overflow AI',
        logo: '',
        initials: 'SO',
        location: 'New York, USA',
        type: 'Corporate Lab',
        memberCount: 20,
        papers: 8,
        citations: 300,
        tags: ['NLP', 'Question Answering'],
        lastActive: '2024-05-13',
        website: 'https://stackoverflow.blog',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'glasgow-ai',
        name: 'University of Glasgow',
        label: 'Glasgow AI',
        logo: '',
        initials: 'UoG',
        location: 'Glasgow, UK',
        type: 'University',
        memberCount: 15,
        papers: 75,
        citations: 4000,
        tags: ['AI', 'Machine Learning', 'Computer Vision'],
        lastActive: '2024-05-12',
        website: 'https://www.gla.ac.uk/ai',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'github-ai',
        name: 'GitHub',
        label: 'GitHub AI',
        logo: '',
        initials: 'GH',
        location: 'San Francisco, USA',
        type: 'Corporate Lab',
        memberCount: 22,
        papers: 6,
        citations: 200,
        tags: ['Code AI', 'Machine Learning'],
        lastActive: '2024-05-15',
        website: 'https://github.blog',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'dundee-ai',
        name: 'University of Dundee',
        label: 'Dundee AI',
        logo: '',
        initials: 'UoD',
        location: 'Dundee, UK',
        type: 'University',
        memberCount: 14,
        papers: 70,
        citations: 3500,
        tags: ['AI', 'Computer Vision', 'Robotics'],
        lastActive: '2024-05-11',
        website: 'https://www.dundee.ac.uk/ai',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'discord-ai',
        name: 'Discord',
        label: 'Discord AI',
        logo: '',
        initials: 'DC',
        location: 'San Francisco, USA',
        type: 'Corporate Lab',
        memberCount: 18,
        papers: 5,
        citations: 150,
        tags: ['NLP', 'Conversational AI'],
        lastActive: '2024-05-14',
        website: 'https://discord.com/blog',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'aberdeen-ai',
        name: 'University of Aberdeen',
        label: 'Aberdeen AI',
        logo: '',
        initials: 'UoA',
        location: 'Aberdeen, UK',
        type: 'University',
        memberCount: 13,
        papers: 65,
        citations: 3000,
        tags: ['AI', 'Machine Learning', 'Computer Vision'],
        lastActive: '2024-05-10',
        website: 'https://www.abdn.ac.uk/ai',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'slack-ai',
        name: 'Slack',
        label: 'Slack AI',
        logo: '',
        initials: 'SLK',
        location: 'San Francisco, USA',
        type: 'Corporate Lab',
        memberCount: 16,
        papers: 4,
        citations: 100,
        tags: ['NLP', 'Conversational AI'],
        lastActive: '2024-05-13',
        website: 'https://slack.com/blog',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'stirling-ai',
        name: 'University of Stirling',
        label: 'Stirling AI',
        logo: '',
        initials: 'UoS',
        location: 'Stirling, UK',
        type: 'University',
        memberCount: 12,
        papers: 60,
        citations: 2500,
        tags: ['AI', 'Computer Vision', 'Robotics'],
        lastActive: '2024-05-12',
        website: 'https://www.stir.ac.uk/ai',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'zoom-ai',
        name: 'Zoom',
        label: 'Zoom AI',
        logo: '',
        initials: 'ZM',
        location: 'San Jose, USA',
        type: 'Corporate Lab',
        memberCount: 14,
        papers: 3,
        citations: 80,
        tags: ['Computer Vision', 'Audio AI'],
        lastActive: '2024-05-15',
        website: 'https://blog.zoom.us',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'strathclyde-ai',
        name: 'University of Strathclyde',
        label: 'Strathclyde AI',
        logo: '',
        initials: 'UoS',
        location: 'Glasgow, UK',
        type: 'University',
        memberCount: 11,
        papers: 55,
        citations: 2000,
        tags: ['AI', 'Machine Learning', 'Computer Vision'],
        lastActive: '2024-05-11',
        website: 'https://www.strath.ac.uk/ai',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'dropbox-ai',
        name: 'Dropbox',
        label: 'Dropbox AI',
        logo: '',
        initials: 'DBX',
        location: 'San Francisco, USA',
        type: 'Corporate Lab',
        memberCount: 12,
        papers: 2,
        citations: 60,
        tags: ['Computer Vision', 'Document AI'],
        lastActive: '2024-05-14',
        website: 'https://blog.dropbox.com',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'heriot-watt-ai',
        name: 'Heriot-Watt University',
        label: 'Heriot-Watt AI',
        logo: '',
        initials: 'HWU',
        location: 'Edinburgh, UK',
        type: 'University',
        memberCount: 10,
        papers: 50,
        citations: 1800,
        tags: ['AI', 'Robotics', 'Computer Vision'],
        lastActive: '2024-05-10',
        website: 'https://www.hw.ac.uk/ai',
        isFavorite: false,
        isAdmin: false
    },
    {
        id: 'box-ai',
        name: 'Box',
        label: 'Box AI',
        logo: '',
        initials: 'BOX',
        location: 'Redwood City, USA',
        type: 'Corporate Lab',
        memberCount: 10,
        papers: 1,
        citations: 40,
        tags: ['Document AI', 'Computer Vision'],
        lastActive: '2024-05-13',
        website: 'https://blog.box.com',
        isFavorite: false,
        isAdmin: false
    }
]; 