import type { Scholar } from './scholars';

export const scholarsN_Z: Scholar[] = [
  {
    id: 'nina-nash',
    name: 'Nina Nash',
    username: '@ninanash',
    avatar: 'NN',
    institution: 'MIT',
    department: 'Mathematics',
    title: 'Research Scientist',
    expertise: ['Natural Language Processing', 'Deep Learning', 'Language Models', 'Text Generation'],
    hIndex: 27,
    totalCitations: 4100,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'mit-csail',
  },
  {
    id: 'oliver-owens',
    name: 'Oliver Owens',
    username: '@oliverowens',
    avatar: 'OO',
    institution: 'OpenAI',
    department: 'Language Models',
    title: 'Principal Scientist',
    expertise: ['Large Language Models', 'AI Safety', 'Alignment', 'Constitutional AI'],
    hIndex: 35,
    totalCitations: 6200,
    papers: [],
    recentActivity: '1 week ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'openai',
  },
  {
    id: 'paula-perez',
    name: 'Paula Perez',
    username: '@paulaperez',
    avatar: 'PP',
    institution: 'Carnegie Mellon University',
    department: 'Machine Learning',
    title: 'Associate Professor',
    expertise: ['Machine Learning', 'Natural Language Processing', 'Information Retrieval', 'Knowledge Graphs'],
    hIndex: 25,
    totalCitations: 3500,
    papers: [],
    recentActivity: '4 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'cmu-ml',
  },
  {
    id: 'quincy-quinn',
    name: 'Quincy Quinn',
    username: '@quincyquinn',
    avatar: 'QQ',
    institution: 'Google',
    department: 'AI Research',
    title: 'Research Scientist',
    expertise: ['Deep Learning', 'TensorFlow', 'Model Optimization', 'Neural Architecture Design'],
    hIndex: 30,
    totalCitations: 5000,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'google-brain',
  },
  {
    id: 'rachel-ryan',
    name: 'Rachel Ryan',
    username: '@rachelryan',
    avatar: 'RR',
    institution: 'University of Oxford',
    department: 'Engineering',
    title: 'Lecturer',
    expertise: ['Robotics', 'Computer Vision', 'Visual SLAM', 'Robotic Perception'],
    hIndex: 18,
    totalCitations: 1800,
    papers: [],
    recentActivity: '5 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'oxford-ai',
  },
  {
    id: 'steven-smith',
    name: 'Steven Smith',
    username: '@stevensmith',
    avatar: 'SS',
    institution: 'Meta',
    department: 'AI Research',
    title: 'Senior Scientist',
    expertise: ['Natural Language Processing', 'Computer Vision', 'Multimodal Learning', 'Vision-Language Models'],
    hIndex: 22,
    totalCitations: 3200,
    papers: [],
    recentActivity: '3 days ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'facebook-ai',
  },
  {
    id: 'tina-tan',
    name: 'Tina Tan',
    username: '@tinanash',
    avatar: 'TT',
    institution: 'University of Toronto',
    department: 'Computer Science',
    title: 'Professor',
    expertise: ['Deep Learning', 'Theoretical Machine Learning', 'Neural Networks', 'Optimization Theory'],
    hIndex: 29,
    totalCitations: 4100,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'toronto-ai',
  },
  {
    id: 'ulrich-ulrich',
    name: 'Ulrich Ulrich',
    username: '@ulrichulrich',
    avatar: 'UU',
    institution: 'Microsoft',
    department: 'AI Research',
    title: 'Principal Researcher',
    expertise: ['AI Systems', 'Distributed Computing', 'Cloud AI', 'Machine Learning Infrastructure'],
    hIndex: 33,
    totalCitations: 5400,
    papers: [],
    recentActivity: '1 week ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'microsoft-research',
  },
  {
    id: 'valerie-vargas',
    name: 'Valerie Vargas',
    username: '@valerievargas',
    avatar: 'VV',
    institution: 'ETH Zurich',
    department: 'Computer Science',
    title: 'Research Scientist',
    expertise: ['Robotics', 'Autonomous Systems', 'Motion Planning', 'Robotic Learning'],
    hIndex: 21,
    totalCitations: 2300,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'eth-zurich',
  },
  {
    id: 'walter-wilson',
    name: 'Walter Wilson',
    username: '@walterwilson',
    avatar: 'WW',
    institution: 'NVIDIA',
    department: 'AI Research',
    title: 'Senior Scientist',
    expertise: ['Computer Graphics', 'Neural Rendering', '3D Vision', 'Generative AI'],
    hIndex: 27,
    totalCitations: 3900,
    papers: [],
    recentActivity: '3 days ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'nvidia-research',
  },
  {
    id: 'xena-xu',
    name: 'Xena Xu',
    username: '@xenaxu',
    avatar: 'XX',
    institution: 'Caltech',
    department: 'Robotics',
    title: 'Assistant Professor',
    expertise: ['Robotics', 'Control Systems', 'Human-Robot Interaction', 'Autonomous Systems'],
    hIndex: 20,
    totalCitations: 1800,
    papers: [],
    recentActivity: '4 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'caltech-ai',
  },
  {
    id: 'yuki-yamamoto',
    name: 'Yuki Yamamoto',
    username: '@yukiyamamoto',
    avatar: 'YY',
    institution: 'Amazon',
    department: 'Cloud AI',
    title: 'Research Scientist',
    expertise: ['Machine Learning', 'Cloud AI', 'Distributed Systems', 'Scalable ML'],
    hIndex: 24,
    totalCitations: 3100,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'amazon-ai',
  },
  {
    id: 'zara-zimmerman',
    name: 'Zara Zimmerman',
    username: '@zarazimmerman',
    avatar: 'ZZ',
    institution: 'UCL',
    department: 'Neuroscience',
    title: 'Lecturer',
    expertise: ['Computational Neuroscience', 'Brain-Computer Interfaces', 'Neural Networks', 'Cognitive Science'],
    hIndex: 18,
    totalCitations: 1700,
    papers: [],
    recentActivity: '5 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'ucl-ai',
  },
  {
    id: 'aaron-anderson',
    name: 'Aaron Anderson',
    username: '@aaronanderson',
    avatar: 'AA',
    institution: 'Apple',
    department: 'AI/ML',
    title: 'Research Scientist',
    expertise: ['Machine Learning', 'Privacy-Preserving ML', 'Federated Learning', 'Differential Privacy'],
    hIndex: 22,
    totalCitations: 2500,
    papers: [],
    recentActivity: '1 week ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'apple-ai',
  },
  {
    id: 'brittany-brown',
    name: 'Brittany Brown',
    username: '@brittanybrown',
    avatar: 'BB',
    institution: 'EPFL',
    department: 'Robotics',
    title: 'Assistant Professor',
    expertise: ['Robotics', 'Swarm Robotics', 'Multi-Robot Systems', 'Bio-Inspired Robotics'],
    hIndex: 19,
    totalCitations: 2100,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'epfl-ai',
  },
  {
    id: 'carlos-cruz',
    name: 'Carlos Cruz',
    username: '@carloscruz',
    avatar: 'CC',
    institution: 'IBM',
    department: 'Quantum Computing',
    title: 'Principal Scientist',
    expertise: ['AI', 'Quantum Computing'],
    hIndex: 31,
    totalCitations: 4700,
    papers: [],
    recentActivity: '3 days ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'ibm-research',
  },
  {
    id: 'diana-davis',
    name: 'Diana Davis',
    username: '@dianadavis',
    avatar: 'DD',
    institution: 'NYU',
    department: 'Computer Vision',
    title: 'Associate Professor',
    expertise: ['AI', 'Computer Vision'],
    hIndex: 26,
    totalCitations: 3200,
    papers: [],
    recentActivity: '4 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'nyu-ai',
  },
  {
    id: 'ethan-edwards',
    name: 'Ethan Edwards',
    username: '@ethanedwards',
    avatar: 'EE',
    institution: 'Salesforce',
    department: 'Enterprise AI',
    title: 'Research Scientist',
    expertise: ['NLP', 'Enterprise AI'],
    hIndex: 23,
    totalCitations: 2800,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'salesforce-ai',
  },
  {
    id: 'fiona-fisher',
    name: 'Fiona Fisher',
    username: '@fionafisher',
    avatar: 'FF',
    institution: 'Cambridge',
    department: 'Robotics',
    title: 'Lecturer',
    expertise: ['AI', 'Robotics'],
    hIndex: 20,
    totalCitations: 1900,
    papers: [],
    recentActivity: '5 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'cambridge-ai',
  },
  {
    id: 'gavin-garcia',
    name: 'Gavin Garcia',
    username: '@gavingarcia',
    avatar: 'GG',
    institution: 'Netflix',
    department: 'Recommendation Systems',
    title: 'Senior Scientist',
    expertise: ['Recommendation Systems', 'Machine Learning'],
    hIndex: 21,
    totalCitations: 2000,
    papers: [],
    recentActivity: '3 days ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'netflix-ai',
  },
  {
    id: 'hazel-harris',
    name: 'Hazel Harris',
    username: '@hazelharris',
    avatar: 'HH',
    institution: 'Imperial College London',
    department: 'Computer Vision',
    title: 'Research Scientist',
    expertise: ['AI', 'Computer Vision'],
    hIndex: 18,
    totalCitations: 1700,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'imperial-ai',
  },
  {
    id: 'ivan-ivanov',
    name: 'Ivan Ivanov',
    username: '@ivanivanov',
    avatar: 'II',
    institution: 'Spotify',
    department: 'Audio AI',
    title: 'Research Scientist',
    expertise: ['Audio AI', 'Recommendation Systems'],
    hIndex: 17,
    totalCitations: 1500,
    papers: [],
    recentActivity: '1 week ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'spotify-ai',
  },
  {
    id: 'jasmine-johnson',
    name: 'Jasmine Johnson',
    username: '@jasminejohnson',
    avatar: 'JJ',
    institution: 'Edinburgh',
    department: 'NLP',
    title: 'Lecturer',
    expertise: ['NLP', 'Machine Learning'],
    hIndex: 19,
    totalCitations: 1600,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'edinburgh-ai',
  },
  {
    id: 'kevin-kumar',
    name: 'Kevin Kumar',
    username: '@kevinkumar',
    avatar: 'KK',
    institution: 'Uber',
    department: 'Autonomous Vehicles',
    title: 'Research Scientist',
    expertise: ['Autonomous Vehicles', 'Machine Learning'],
    hIndex: 16,
    totalCitations: 1400,
    papers: [],
    recentActivity: '3 days ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'uber-ai',
  },
  {
    id: 'luna-lewis',
    name: 'Luna Lewis',
    username: '@lunalewis',
    avatar: 'LL',
    institution: 'Manchester',
    department: 'Computer Vision',
    title: 'Lecturer',
    expertise: ['AI', 'Computer Vision'],
    hIndex: 15,
    totalCitations: 1300,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'manchester-ai',
  },
  {
    id: 'marcus-martinez',
    name: 'Marcus Martinez',
    username: '@marcusmartinez',
    avatar: 'MM',
    institution: 'Airbnb',
    department: 'Computer Vision',
    title: 'Research Scientist',
    expertise: ['Computer Vision', 'Recommendation Systems'],
    hIndex: 14,
    totalCitations: 1200,
    papers: [],
    recentActivity: '1 week ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'airbnb-ai',
  },
  {
    id: 'nora-nelson',
    name: 'Nora Nelson',
    username: '@noranelson',
    avatar: 'NN',
    institution: 'Bristol',
    department: 'Robotics',
    title: 'Lecturer',
    expertise: ['AI', 'Robotics'],
    hIndex: 13,
    totalCitations: 1100,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'bristol-ai',
  },
  {
    id: 'oscar-ortiz',
    name: 'Oscar Ortiz',
    username: '@oscarortiz',
    avatar: 'OO',
    institution: 'LinkedIn',
    department: 'NLP',
    title: 'Research Scientist',
    expertise: ['NLP', 'Recommendation Systems'],
    hIndex: 12,
    totalCitations: 1000,
    papers: [],
    recentActivity: '3 days ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'linkedin-ai',
  },
  {
    id: 'penny-peterson',
    name: 'Penny Peterson',
    username: '@pennypeterson',
    avatar: 'PP',
    institution: 'Warwick',
    department: 'Machine Learning',
    title: 'Lecturer',
    expertise: ['AI', 'Machine Learning'],
    hIndex: 11,
    totalCitations: 900,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'warwick-ai',
  },
  {
    id: 'quinn-quincy',
    name: 'Quinn Quincy',
    username: '@quinnquincy',
    avatar: 'QQ',
    institution: 'Twitter',
    department: 'NLP',
    title: 'Research Scientist',
    expertise: ['NLP', 'Recommendation Systems'],
    hIndex: 10,
    totalCitations: 800,
    papers: [],
    recentActivity: '1 week ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'twitter-ai',
  },
  {
    id: 'riley-rodriguez',
    name: 'Riley Rodriguez',
    username: '@rileyrodriguez',
    avatar: 'RR',
    institution: 'Sheffield',
    department: 'Machine Learning',
    title: 'Lecturer',
    expertise: ['NLP', 'Machine Learning'],
    hIndex: 9,
    totalCitations: 700,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'sheffield-ai',
  },
  {
    id: 'sophia-singh',
    name: 'Sophia Singh',
    username: '@sophiasingh',
    avatar: 'SS',
    institution: 'Snap Inc.',
    department: 'AR/VR',
    title: 'Research Scientist',
    expertise: ['Computer Vision', 'AR/VR'],
    hIndex: 8,
    totalCitations: 600,
    papers: [],
    recentActivity: '3 days ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'snap-ai',
  },
  {
    id: 'theo-thompson',
    name: 'Theo Thompson',
    username: '@theothompson',
    avatar: 'TT',
    institution: 'Leeds',
    department: 'Robotics',
    title: 'Lecturer',
    expertise: ['AI', 'Robotics'],
    hIndex: 7,
    totalCitations: 500,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'leeds-ai',
  },
  {
    id: 'una-umara',
    name: 'Una Umara',
    username: '@unaumara',
    avatar: 'UU',
    institution: 'Pinterest',
    department: 'Computer Vision',
    title: 'Research Scientist',
    expertise: ['Computer Vision', 'Recommendation Systems'],
    hIndex: 6,
    totalCitations: 400,
    papers: [],
    recentActivity: '1 week ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'pinterest-ai',
  },
  {
    id: 'vince-vasquez',
    name: 'Vince Vasquez',
    username: '@vincevasquez',
    avatar: 'VV',
    institution: 'Liverpool',
    department: 'Machine Learning',
    title: 'Lecturer',
    expertise: ['AI', 'Machine Learning'],
    hIndex: 5,
    totalCitations: 300,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'liverpool-ai',
  },
  {
    id: 'willa-williams',
    name: 'Willa Williams',
    username: '@willawilliams',
    avatar: 'WW',
    institution: 'Yelp',
    department: 'NLP',
    title: 'Research Scientist',
    expertise: ['NLP', 'Recommendation Systems'],
    hIndex: 4,
    totalCitations: 200,
    papers: [],
    recentActivity: '3 days ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'yelp-ai',
  },
  {
    id: 'xander-xavier',
    name: 'Xander Xavier',
    username: '@xanderxavier',
    avatar: 'XX',
    institution: 'Nottingham',
    department: 'Computer Vision',
    title: 'Lecturer',
    expertise: ['AI', 'Computer Vision'],
    hIndex: 3,
    totalCitations: 100,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'nottingham-ai',
  },
  {
    id: 'yara-yates',
    name: 'Yara Yates',
    username: '@yarayates',
    avatar: 'YY',
    institution: 'Reddit',
    department: 'NLP',
    title: 'Research Scientist',
    expertise: ['NLP', 'Recommendation Systems'],
    hIndex: 2,
    totalCitations: 50,
    papers: [],
    recentActivity: '1 week ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'reddit-ai',
  },
  {
    id: 'zane-zimmerman',
    name: 'Zane Zimmerman',
    username: '@zanezimmerman',
    avatar: 'ZZ',
    institution: 'Birmingham',
    department: 'Machine Learning',
    title: 'Lecturer',
    expertise: ['AI', 'Machine Learning'],
    hIndex: 1,
    totalCitations: 25,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'birmingham-ai',
  },
]; 