import type { Scholar } from './scholars';

export const scholarsA_M: Scholar[] = [
  {
    id: 'alex-abbott',
    name: 'Alex Abbott',
    username: '@alexabbott',
    avatar: 'AA',
    institution: 'Stanford University',
    department: 'Computer Science',
    title: 'Professor',
    expertise: ['Transformer Architecture', 'Attention Mechanisms', 'Neural Networks', 'Deep Learning'],
    hIndex: 32,
    totalCitations: 5200,
    papers: [],
    recentActivity: '1 day ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'stanford-ai-lab',
  },
  {
    id: 'bella-baker',
    name: 'Bella Baker',
    username: '@bellabaker',
    avatar: 'BB',
    institution: 'DeepMind',
    department: 'AI Research',
    title: 'Research Scientist',
    expertise: ['Reinforcement Learning', 'Multi-Agent Systems', 'Game Theory', 'Neuroscience'],
    hIndex: 28,
    totalCitations: 4100,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'deepmind',
  },
  {
    id: 'carla-chen',
    name: 'Carla Chen',
    username: '@carlachen',
    avatar: 'CC',
    institution: 'UC Berkeley',
    department: 'Electrical Engineering',
    title: 'Assistant Professor',
    expertise: ['Computer Vision', 'Object Detection', 'Semantic Segmentation', 'Robotics'],
    hIndex: 19,
    totalCitations: 2100,
    papers: [],
    recentActivity: '3 days ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'berkeley-ai',
  },
  {
    id: 'daniel-diaz',
    name: 'Daniel Diaz',
    username: '@danieldiaz',
    avatar: 'DD',
    institution: 'MIT',
    department: 'Mathematics',
    title: 'Professor',
    expertise: ['Theoretical Machine Learning', 'Optimization Theory', 'Statistical Learning', 'Complexity Theory'],
    hIndex: 40,
    totalCitations: 8000,
    papers: [],
    recentActivity: '1 week ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'mit-csail',
  },
  {
    id: 'emma-evans',
    name: 'Emma Evans',
    username: '@emmaevans',
    avatar: 'EE',
    institution: 'OpenAI',
    department: 'Language Models',
    title: 'Principal Scientist',
    expertise: ['Large Language Models', 'AI Safety', 'Alignment', 'Prompt Engineering'],
    hIndex: 35,
    totalCitations: 6200,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'openai',
  },
  {
    id: 'felix-foster',
    name: 'Felix Foster',
    username: '@felixfoster',
    avatar: 'FF',
    institution: 'Carnegie Mellon University',
    department: 'Machine Learning',
    title: 'Associate Professor',
    expertise: ['Natural Language Processing', 'Information Extraction', 'Question Answering', 'Machine Learning'],
    hIndex: 25,
    totalCitations: 3500,
    papers: [],
    recentActivity: '4 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'cmu-ml',
  },
  {
    id: 'grace-garcia',
    name: 'Grace Garcia',
    username: '@gracegarcia',
    avatar: 'GG',
    institution: 'Google',
    department: 'AI Research',
    title: 'Research Scientist',
    expertise: ['Deep Learning', 'Neural Architecture Search', 'AutoML', 'TensorFlow'],
    hIndex: 30,
    totalCitations: 5000,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'google-brain',
  },
  {
    id: 'hannah-hughes',
    name: 'Hannah Hughes',
    username: '@hannahhughes',
    avatar: 'HH',
    institution: 'University of Oxford',
    department: 'Engineering',
    title: 'Lecturer',
    expertise: ['Robotics', 'Computer Vision', 'SLAM', 'Autonomous Navigation'],
    hIndex: 18,
    totalCitations: 1800,
    papers: [],
    recentActivity: '5 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'oxford-ai',
  },
  {
    id: 'ian-irving',
    name: 'Ian Irving',
    username: '@ianirving',
    avatar: 'II',
    institution: 'Meta',
    department: 'AI Research',
    title: 'Senior Scientist',
    expertise: ['Natural Language Processing', 'Computer Vision', 'Multimodal Learning', 'Social Media AI'],
    hIndex: 22,
    totalCitations: 3200,
    papers: [],
    recentActivity: '3 days ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'facebook-ai',
  },
  {
    id: 'julia-jones',
    name: 'Julia Jones',
    username: '@julia',
    avatar: 'JJ',
    institution: 'University of Toronto',
    department: 'Computer Science',
    title: 'Professor',
    expertise: ['Deep Learning', 'Theoretical Machine Learning', 'Neural Networks', 'Representation Learning'],
    hIndex: 29,
    totalCitations: 4100,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'toronto-ai',
  },
  {
    id: 'karen-kim',
    name: 'Karen Kim',
    username: '@karenkim',
    avatar: 'KK',
    institution: 'Microsoft',
    department: 'AI Research',
    title: 'Principal Researcher',
    expertise: ['AI Systems', 'Distributed Computing', 'Cloud AI', 'Machine Learning Infrastructure'],
    hIndex: 33,
    totalCitations: 5400,
    papers: [],
    recentActivity: '1 week ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'microsoft-research',
  },
  {
    id: 'liam-lee',
    name: 'Liam Lee',
    username: '@liamlee',
    avatar: 'LL',
    institution: 'ETH Zurich',
    department: 'Computer Science',
    title: 'Research Scientist',
    expertise: ['Robotics', 'AI'],
    hIndex: 21,
    totalCitations: 2300,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'eth-zurich',
  },
  {
    id: 'maya-martin',
    name: 'Maya Martin',
    username: '@mayamartin',
    avatar: 'MM',
    institution: 'NVIDIA',
    department: 'AI Research',
    title: 'Senior Scientist',
    expertise: ['Computer Graphics', 'Neural Rendering', '3D Vision', 'Generative AI'],
    hIndex: 27,
    totalCitations: 3900,
    papers: [],
    recentActivity: '3 days ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'nvidia-research',
  },
  {
    id: 'noah-nguyen',
    name: 'Noah Nguyen',
    username: '@noahnguyen',
    avatar: 'NN',
    institution: 'Caltech',
    department: 'Robotics',
    title: 'Assistant Professor',
    expertise: ['Robotics', 'Control Systems', 'Human-Robot Interaction', 'Autonomous Systems'],
    hIndex: 20,
    totalCitations: 1800,
    papers: [],
    recentActivity: '4 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'caltech-ai',
  },
  {
    id: 'olivia-owens',
    name: 'Olivia Owens',
    username: '@oliviaowens',
    avatar: 'OO',
    institution: 'Amazon',
    department: 'Cloud AI',
    title: 'Research Scientist',
    expertise: ['Machine Learning', 'Cloud AI', 'Distributed Systems', 'Scalable ML'],
    hIndex: 24,
    totalCitations: 3100,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'amazon-ai',
  },
  {
    id: 'paul-patel',
    name: 'Paul Patel',
    username: '@paulpatel',
    avatar: 'PP',
    institution: 'UCL',
    department: 'Neuroscience',
    title: 'Lecturer',
    expertise: ['Computational Neuroscience', 'Brain-Computer Interfaces', 'Neural Networks', 'Cognitive Science'],
    hIndex: 18,
    totalCitations: 1700,
    papers: [],
    recentActivity: '5 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'ucl-ai',
  },
  {
    id: 'quinn-quinn',
    name: 'Quinn Quinn',
    username: '@quinnquinn',
    avatar: 'QQ',
    institution: 'Apple',
    department: 'AI/ML',
    title: 'Research Scientist',
    expertise: ['Machine Learning', 'Privacy-Preserving ML', 'Federated Learning', 'Differential Privacy'],
    hIndex: 22,
    totalCitations: 2500,
    papers: [],
    recentActivity: '1 week ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'apple-ai',
  },
  {
    id: 'ruby-ramirez',
    name: 'Ruby Ramirez',
    username: '@rubyramirez',
    avatar: 'RR',
    institution: 'EPFL',
    department: 'Robotics',
    title: 'Assistant Professor',
    expertise: ['Robotics', 'Swarm Robotics', 'Multi-Robot Systems', 'Bio-Inspired Robotics'],
    hIndex: 19,
    totalCitations: 2100,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'epfl-ai',
  },
  {
    id: 'sam-sanders',
    name: 'Sam Sanders',
    username: '@samsanders',
    avatar: 'SS',
    institution: 'IBM',
    department: 'Quantum Computing',
    title: 'Principal Scientist',
    expertise: ['Quantum Machine Learning', 'Quantum Computing', 'Quantum Algorithms', 'Quantum-Classical Hybrid Systems'],
    hIndex: 31,
    totalCitations: 4700,
    papers: [],
    recentActivity: '3 days ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'ibm-research',
  },
  {
    id: 'tara-thompson',
    name: 'Tara Thompson',
    username: '@tarathompson',
    avatar: 'TT',
    institution: 'NYU',
    department: 'Computer Vision',
    title: 'Associate Professor',
    expertise: ['Computer Vision', 'Medical Imaging', 'Biomedical AI', 'Image Analysis'],
    hIndex: 26,
    totalCitations: 3200,
    papers: [],
    recentActivity: '4 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'nyu-ai',
  },
  {
    id: 'uma-underwood',
    name: 'Uma Underwood',
    username: '@umaunderwood',
    avatar: 'UU',
    institution: 'Salesforce',
    department: 'Enterprise AI',
    title: 'Research Scientist',
    expertise: ['Natural Language Processing', 'Enterprise AI', 'Business Intelligence', 'Text Analytics'],
    hIndex: 23,
    totalCitations: 2800,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'salesforce-ai',
  },
  {
    id: 'victor-vargas',
    name: 'Victor Vargas',
    username: '@victorvargas',
    avatar: 'VV',
    institution: 'Cambridge',
    department: 'Robotics',
    title: 'Lecturer',
    expertise: ['Robotics', 'Soft Robotics', 'Wearable Robotics', 'Rehabilitation Robotics'],
    hIndex: 20,
    totalCitations: 1900,
    papers: [],
    recentActivity: '5 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'cambridge-ai',
  },
  {
    id: 'wendy-wilson',
    name: 'Wendy Wilson',
    username: '@wendywilson',
    avatar: 'WW',
    institution: 'Netflix',
    department: 'Recommendation Systems',
    title: 'Senior Scientist',
    expertise: ['Recommendation Systems', 'Personalization', 'Content Discovery', 'Machine Learning'],
    hIndex: 21,
    totalCitations: 2000,
    papers: [],
    recentActivity: '3 days ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'netflix-ai',
  },
  {
    id: 'xander-xu',
    name: 'Xander Xu',
    username: '@xanderxu',
    avatar: 'XX',
    institution: 'Imperial College London',
    department: 'Computer Vision',
    title: 'Research Scientist',
    expertise: ['AI', 'Computer Vision'],
    hIndex: 18,
    totalCitations: 1700,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'imperial-ai',
  },
  {
    id: 'yara-young',
    name: 'Yara Young',
    username: '@yarayoung',
    avatar: 'YY',
    institution: 'Spotify',
    department: 'Audio AI',
    title: 'Research Scientist',
    expertise: ['Audio AI', 'Recommendation Systems'],
    hIndex: 17,
    totalCitations: 1500,
    papers: [],
    recentActivity: '1 week ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'spotify-ai',
  },
  {
    id: 'zoe-zimmerman',
    name: 'Zoe Zimmerman',
    username: '@zoezimmerman',
    avatar: 'ZZ',
    institution: 'Edinburgh',
    department: 'NLP',
    title: 'Lecturer',
    expertise: ['NLP', 'Machine Learning'],
    hIndex: 19,
    totalCitations: 1600,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'edinburgh-ai',
  },
  {
    id: 'abby-allen',
    name: 'Abby Allen',
    username: '@abbyallen',
    avatar: 'AA',
    institution: 'Uber',
    department: 'Autonomous Vehicles',
    title: 'Research Scientist',
    expertise: ['Autonomous Vehicles', 'Machine Learning'],
    hIndex: 16,
    totalCitations: 1400,
    papers: [],
    recentActivity: '3 days ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'uber-ai',
  },
  {
    id: 'ben-brooks',
    name: 'Ben Brooks',
    username: '@benbrooks',
    avatar: 'BB',
    institution: 'Manchester',
    department: 'Computer Vision',
    title: 'Lecturer',
    expertise: ['AI', 'Computer Vision'],
    hIndex: 15,
    totalCitations: 1300,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'manchester-ai',
  },
  {
    id: 'carmen-carter',
    name: 'Carmen Carter',
    username: '@carmencarter',
    avatar: 'CC',
    institution: 'Airbnb',
    department: 'Computer Vision',
    title: 'Research Scientist',
    expertise: ['Computer Vision', 'Recommendation Systems'],
    hIndex: 14,
    totalCitations: 1200,
    papers: [],
    recentActivity: '1 week ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'airbnb-ai',
  },
  {
    id: 'derek-dunn',
    name: 'Derek Dunn',
    username: '@derekdunn',
    avatar: 'DD',
    institution: 'Bristol',
    department: 'Robotics',
    title: 'Lecturer',
    expertise: ['AI', 'Robotics'],
    hIndex: 13,
    totalCitations: 1100,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'bristol-ai',
  },
  {
    id: 'elena-ellis',
    name: 'Elena Ellis',
    username: '@elenaellis',
    avatar: 'EE',
    institution: 'LinkedIn',
    department: 'NLP',
    title: 'Research Scientist',
    expertise: ['NLP', 'Recommendation Systems'],
    hIndex: 12,
    totalCitations: 1000,
    papers: [],
    recentActivity: '3 days ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'linkedin-ai',
  },
  {
    id: 'frank-farrell',
    name: 'Frank Farrell',
    username: '@frankfarrell',
    avatar: 'FF',
    institution: 'Warwick',
    department: 'Machine Learning',
    title: 'Lecturer',
    expertise: ['AI', 'Machine Learning'],
    hIndex: 11,
    totalCitations: 900,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'warwick-ai',
  },
  {
    id: 'george-gibson',
    name: 'George Gibson',
    username: '@georgegibson',
    avatar: 'GG',
    institution: 'Twitter',
    department: 'NLP',
    title: 'Research Scientist',
    expertise: ['NLP', 'Recommendation Systems'],
    hIndex: 10,
    totalCitations: 800,
    papers: [],
    recentActivity: '1 week ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'twitter-ai',
  },
  {
    id: 'harper-hall',
    name: 'Harper Hall',
    username: '@harperhall',
    avatar: 'HH',
    institution: 'Sheffield',
    department: 'Machine Learning',
    title: 'Lecturer',
    expertise: ['NLP', 'Machine Learning'],
    hIndex: 9,
    totalCitations: 700,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'sheffield-ai',
  },
  {
    id: 'isabel-isaacs',
    name: 'Isabel Isaacs',
    username: '@isabelisaacs',
    avatar: 'II',
    institution: 'Snap Inc.',
    department: 'AR/VR',
    title: 'Research Scientist',
    expertise: ['Computer Vision', 'AR/VR'],
    hIndex: 8,
    totalCitations: 600,
    papers: [],
    recentActivity: '3 days ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'snap-ai',
  },
  {
    id: 'jack-jordan',
    name: 'Jack Jordan',
    username: '@jackjordan',
    avatar: 'JJ',
    institution: 'Leeds',
    department: 'Robotics',
    title: 'Lecturer',
    expertise: ['AI', 'Robotics'],
    hIndex: 7,
    totalCitations: 500,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'leeds-ai',
  },
  {
    id: 'kyle-kent',
    name: 'Kyle Kent',
    username: '@kylekent',
    avatar: 'KK',
    institution: 'Pinterest',
    department: 'Computer Vision',
    title: 'Research Scientist',
    expertise: ['Computer Vision', 'Recommendation Systems'],
    hIndex: 6,
    totalCitations: 400,
    papers: [],
    recentActivity: '1 week ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'pinterest-ai',
  },
  {
    id: 'lisa-lane',
    name: 'Lisa Lane',
    username: '@lisalane',
    avatar: 'LL',
    institution: 'Liverpool',
    department: 'Machine Learning',
    title: 'Lecturer',
    expertise: ['AI', 'Machine Learning'],
    hIndex: 5,
    totalCitations: 300,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'liverpool-ai',
  },
  {
    id: 'mason-morris',
    name: 'Mason Morris',
    username: '@masonmorris',
    avatar: 'MM',
    institution: 'Yelp',
    department: 'NLP',
    title: 'Research Scientist',
    expertise: ['NLP', 'Recommendation Systems'],
    hIndex: 4,
    totalCitations: 200,
    papers: [],
    recentActivity: '3 days ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'yelp-ai',
  },
  {
    id: 'natalie-nash',
    name: 'Natalie Nash',
    username: '@natalienash',
    avatar: 'NN',
    institution: 'Nottingham',
    department: 'Computer Vision',
    title: 'Lecturer',
    expertise: ['AI', 'Computer Vision'],
    hIndex: 3,
    totalCitations: 100,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'nottingham-ai',
  },
  {
    id: 'oliver-ochoa',
    name: 'Oliver Ochoa',
    username: '@oliverochoa',
    avatar: 'OO',
    institution: 'Reddit',
    department: 'NLP',
    title: 'Research Scientist',
    expertise: ['NLP', 'Recommendation Systems'],
    hIndex: 2,
    totalCitations: 50,
    papers: [],
    recentActivity: '1 week ago',
    isFollowing: false,
    claimed: true,
    affiliationId: 'reddit-ai',
  },
  {
    id: 'paige-parker',
    name: 'Paige Parker',
    username: '@paigeparker',
    avatar: 'PP',
    institution: 'Birmingham',
    department: 'Machine Learning',
    title: 'Lecturer',
    expertise: ['AI', 'Machine Learning'],
    hIndex: 1,
    totalCitations: 25,
    papers: [],
    recentActivity: '2 days ago',
    isFollowing: true,
    claimed: false,
    affiliationId: 'birmingham-ai',
  },
]; 