export interface User {
    id: string;
    name: string;
    avatar: string;
    email: string;
}

export const mockUsers: User[] = [
    { id: 'u1', name: 'Alice', avatar: 'A', email: 'alice@example.com' },
    { id: 'u2', name: 'Bob', avatar: 'B', email: 'bob@example.com' },
    { id: 'u3', name: 'Carol', avatar: 'C', email: 'carol@example.com' },
    { id: 'u4', name: 'David', avatar: 'D', email: 'david@example.com' },
    { id: 'u5', name: 'Eva', avatar: 'E', email: 'eva@example.com' },
    { id: 'u6', name: 'Frank', avatar: 'F', email: 'frank@example.com' },
    { id: 'u7', name: 'Grace', avatar: 'G', email: 'grace@example.com' },
    { id: 'u8', name: 'Henry', avatar: 'H', email: 'henry@example.com' },
    { id: 'u9', name: 'Iris', avatar: 'I', email: 'iris@example.com' },
    { id: 'u10', name: 'Jack', avatar: 'J', email: 'jack@example.com' },
    { id: 'u11', name: 'Kate', avatar: 'K', email: 'kate@example.com' },
    { id: 'u12', name: 'Liam', avatar: 'L', email: 'liam@example.com' },
    { id: 'u13', name: 'Maya', avatar: 'M', email: 'maya@example.com' },
    { id: 'u14', name: 'Noah', avatar: 'N', email: 'noah@example.com' },
    { id: 'u15', name: 'Olivia', avatar: 'O', email: 'olivia@example.com' },
    { id: 'u16', name: 'Paul', avatar: 'P', email: 'paul@example.com' },
    { id: 'u17', name: 'Quinn', avatar: 'Q', email: 'quinn@example.com' },
    { id: 'u18', name: 'Ruby', avatar: 'R', email: 'ruby@example.com' },
    { id: 'u19', name: 'Sam', avatar: 'S', email: 'sam@example.com' },
    { id: 'u20', name: 'Tara', avatar: 'T', email: 'tara@example.com' },
    { id: 'u21', name: 'Uma', avatar: 'U', email: 'uma@example.com' },
    { id: 'u22', name: 'Victor', avatar: 'V', email: 'victor@example.com' },
    { id: 'u23', name: 'Wendy', avatar: 'W', email: 'wendy@example.com' },
    { id: 'u24', name: 'Xavier', avatar: 'X', email: 'xavier@example.com' },
    { id: 'u25', name: 'Yara', avatar: 'Y', email: 'yara@example.com' },
    { id: 'u26', name: 'Zoe', avatar: 'Z', email: 'zoe@example.com' },
    { id: 'u27', name: 'Alex', avatar: 'A', email: 'alex@example.com' },
    { id: 'u28', name: 'Blake', avatar: 'B', email: 'blake@example.com' },
    { id: 'u29', name: 'Casey', avatar: 'C', email: 'casey@example.com' },
    { id: 'u30', name: 'Drew', avatar: 'D', email: 'drew@example.com' },
    { id: 'u31', name: 'Emery', avatar: 'E', email: 'emery@example.com' },
    { id: 'u32', name: 'Finley', avatar: 'F', email: 'finley@example.com' },
    { id: 'u33', name: 'Gray', avatar: 'G', email: 'gray@example.com' },
    { id: 'u34', name: 'Harper', avatar: 'H', email: 'harper@example.com' },
    { id: 'u35', name: 'Indigo', avatar: 'I', email: 'indigo@example.com' },
    { id: 'u36', name: 'Jordan', avatar: 'J', email: 'jordan@example.com' },
    { id: 'u37', name: 'Kendall', avatar: 'K', email: 'kendall@example.com' },
    { id: 'u38', name: 'Logan', avatar: 'L', email: 'logan@example.com' },
    { id: 'u39', name: 'Morgan', avatar: 'M', email: 'morgan@example.com' },
    { id: 'u40', name: 'Nova', avatar: 'N', email: 'nova@example.com' },
    { id: 'u41', name: 'Ocean', avatar: 'O', email: 'ocean@example.com' },
    { id: 'u42', name: 'Parker', avatar: 'P', email: 'parker@example.com' },
    { id: 'u43', name: 'Quincy', avatar: 'Q', email: 'quincy@example.com' },
    { id: 'u44', name: 'River', avatar: 'R', email: 'river@example.com' },
    { id: 'u45', name: 'Sage', avatar: 'S', email: 'sage@example.com' },
    { id: 'u46', name: 'Taylor', avatar: 'T', email: 'taylor@example.com' },
    { id: 'u47', name: 'Unity', avatar: 'U', email: 'unity@example.com' },
    { id: 'u48', name: 'Valor', avatar: 'V', email: 'valor@example.com' },
    { id: 'u49', name: 'Winter', avatar: 'W', email: 'winter@example.com' },
    { id: 'u50', name: 'Xander', avatar: 'X', email: 'xander@example.com' },
]; 