name: all_curriculums
algorithm: discrete_random

# This is a hierarchical curriculum that references other curriculums
children:
  - /env/mettagrid/curriculum/arena/learning_progress
  - /env/mettagrid/curriculum/navigation/prioritize_regressed
  - /env/mettagrid/curriculum/object_use

env_overrides:
  game:
    num_agents: 24