name: resources_curriculum
algorithm: discrete_random

env_paths:
  - /env/mettagrid/arena/advanced_easy

parameters:
  game.agent.rewards.ore_red:
    values: [0, 0.5, 1]
  game.agent.rewards.battery_red:
    values: [0, 0.5, 1]
  game.agent.rewards.heart:
    values: [0, 0.5, 1]