#!/usr/bin/env python3
"""
Test script for tribal environment genny bindings.

This tests the high-performance Nim→Python bindings generated by genny.
"""

import sys

import numpy as np


def test_genny_bindings():
    """Test the genny-generated tribal bindings."""
    print("🧪 Testing Tribal Environment Genny Bindings")
    print("=" * 55)

    # Test 1: Import tribal package
    print("1. Testing tribal package imports...")
    try:
        from metta.tribal.tribal_genny import make_tribal_env

        print("✅ Tribal package imported successfully")
    except ImportError as e:
        print(f"❌ Tribal package import failed: {e}")
        print("   Run: cd tribal && ./build_bindings.sh")
        return False

    # Test 2: Create environment
    print("2. Creating tribal environment...")
    try:
        env = make_tribal_env(max_steps=100)
        print("✅ Environment created")
        print(f"   - Agents: {env.num_agents}")
        print(f"   - Observation width: {env.obs_width}")
        print(f"   - Observation height: {env.obs_height}")
        print(f"   - Action names: {env.action_names}")
    except Exception as e:
        print(f"❌ Environment creation failed: {e}")
        return False

    # Test 3: Reset environment
    print("3. Testing environment reset...")
    try:
        obs, info = env.reset(seed=42)
        print("✅ Reset successful")
        print(f"   - Observation shape: {obs.shape}")
        print(f"   - Info: {info}")

        expected_shape = (15, 200, 3)  # [agents, max_tokens, features]
        if obs.shape == expected_shape:
            print("✅ Observation shape correct")
        else:
            print(f"⚠️  Observation shape: got {obs.shape}, expected {expected_shape}")

    except Exception as e:
        print(f"❌ Reset failed: {e}")
        return False

    # Test 4: Step environment
    print("4. Testing environment step...")
    try:
        # Create safe actions: [action_type, argument]
        actions = np.zeros((15, 2), dtype=np.uint8)
        actions[:, 0] = 1  # Move action
        actions[:, 1] = np.random.randint(0, 8, size=15)  # Random directions

        obs, rewards, terminals, truncations, info = env.step(actions)

        print("✅ Step successful")
        print(f"   - Observations: {obs.shape}")
        print(f"   - Rewards: {rewards.shape}, sum={rewards.sum():.3f}")
        print(f"   - Terminals: {terminals.sum()} agents")
        print(f"   - Step: {info.get('current_step', 'unknown')}")

    except Exception as e:
        print(f"❌ Step failed: {e}")
        return False

    # Test 5: Multiple steps with different actions
    print("5. Testing action variety...")
    try:
        action_types = [0, 1, 2, 3, 4, 5]  # All available actions

        for step in range(5):
            actions = np.zeros((15, 2), dtype=np.uint8)
            actions[:, 0] = np.random.choice(action_types, size=15)
            actions[:, 1] = np.random.randint(0, 8, size=15)  # Random arguments

            obs, rewards, terminals, truncations, info = env.step(actions)

            unique_actions = np.unique(actions[:, 0])
            reward_sum = rewards.sum()
            print(f"   Step {step + 1}: actions={unique_actions}, rewards={reward_sum:.3f}")

        print("✅ Action variety test passed")

    except Exception as e:
        print(f"❌ Action variety test failed: {e}")
        return False

    # Test 6: Environment info
    print("6. Testing environment information...")
    try:
        current_step = env.current_step
        max_steps = env.max_steps
        is_done = env.done

        print("✅ Environment info accessible")
        print(f"   - Current step: {current_step}")
        print(f"   - Max steps: {max_steps}")
        print(f"   - Episode done: {is_done}")

    except Exception as e:
        print(f"❌ Environment info test failed: {e}")
        return False

    print()
    print("🎉 All genny binding tests passed!")
    print()
    print("Performance benefits of genny bindings:")
    print("• Direct Nim→Python object mapping")
    print("• No JSON serialization overhead")
    print("• Native Python lists/objects")
    print("• Automatic memory management")
    print()
    print("Ready for high-performance RL training!")
    print()
    print("Next steps:")
    print("1. Run: uv run ./tools/run.py experiments.recipes.tribal_basic.train run=test_genny")
    print("2. Monitor performance vs pure Python implementations")

    return True


def test_genny_bindings_pytest():
    """Pytest-compatible wrapper for test_genny_bindings."""
    result = test_genny_bindings()
    assert result, "Genny bindings test failed"


if __name__ == "__main__":
    success = test_genny_bindings()
    sys.exit(0 if success else 1)
