#!/bin/bash
# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/format_script_tools.sh"

# Initialize variables with default exclusion pattern
EXCLUDE_PATTERN="$(
  printf '%s\|' \
    '/charts/' \
    'packages/mettagrid/python/src/mettagrid/renderer/assets/' \
    'packages/mettagrid/nim/mettascope/data/'
)"
# strip trailing \|
EXCLUDE_PATTERN="${EXCLUDE_PATTERN%\\|}"

EXCLUDE_HELP_TEXT="  Default: excludes paths known to contain autogenerated json files
  Use --exclude none to format all files"

# Note that this script assumes that a .prettierrc is present with appropriate settings for
# regular json files and vscode's flavor of jsonc

# Parse command line arguments
parse_format_args "$@"

# Ensure required tools are available
ensure_pnpm
ensure_prettier

# Format JSON files
format_files "json"

# Determine mode for final message
if [ "${CHECK_MODE:-false}" = "true" ]; then
  mode_past="checked"
else
  mode_past="formatted"
fi

# Also format .code-workspace files
if [ -f "metta.code-workspace" ]; then
  prettier_mode="--write"
  action="Formatting"
  if [ "${CHECK_MODE:-false}" = "true" ]; then
    prettier_mode="--check"
    action="Checking"
  fi
  echo "$action metta.code-workspace..."
  pnpm exec prettier $prettier_mode metta.code-workspace
fi

echo "All JSON files (except excluded ones) have been $mode_past with Prettier."
