#!/bin/bash
# Get the directory where this script is located
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/format_script_tools.sh"

# Initialize variables with default exclusion pattern
EXCLUDE_PATTERN="$(
  printf '%s\|' \
    '/configs/' \
    '/scenes/' \
    '/charts/' \
    '.github/actions/asana/pr_gh_to_asana/test/'
)"
# strip trailing \|
EXCLUDE_PATTERN="${EXCLUDE_PATTERN%\\|}"

EXCLUDE_HELP_TEXT="  Default: excludes paths known to contain autogenerated yaml files
  Use --exclude none to format all files"

# Parse command line arguments
parse_format_args "$@"

# Ensure required tools are available
ensure_pnpm
ensure_prettier

# Determine mode for messages
if [ "${CHECK_MODE:-false}" = "true" ]; then
  mode_action="checking"
  mode_past="checked"
else
  mode_action="formatting"
  mode_past="formatted"
fi

# Show what exclusion pattern is being used
if [ -n "$EXCLUDE_PATTERN" ]; then
  echo "Using exclusion pattern: $EXCLUDE_PATTERN"
else
  echo "No exclusion pattern - $mode_action all YAML files"
fi
echo ""

# Format YAML files
format_files "yml"
format_files "yaml"

echo ""
echo "All matching YAML files have been $mode_past with Prettier."
