_target_: mettagrid.curriculum.BucketedCurriculum

env_cfg_template: /env/mettagrid/navigation_sequence/experiments/terrain

buckets:
  game.agent.ore.red_max:
    range: [2, 15]
    bins: 2
  game.agent.battery.red_max:
    range: [2, 15]
    bins: 2
  game.agent.rewards.ore.red:
    range: [0.005, 0.05]
    bins: 2
  game.agent.rewards.battery.red:
    range: [0.01, 0.1]
    bins: 2
  game.map_builder.room.width:
    range: [15, 100]
    bins: 2
  game.map_builder.room.height:
    range: [15, 100]
    bins: 2
  game.map_builder.room.style:
    values: [maze]
  game.map_builder.room.objects.mine.red:
    range: [2, 15]
    bins: 2
  game.map_builder.room.objects.generator.red:
    range: [2, 15]
    bins: 2
  game.objects.altar.initial_items:
    range: [0, 1]
  game.objects.generator.red.initial_items:
    range: [0, 1]
  game.objects.mine.red.cooldown:
    range: [15, 50]
    bins: 2
  game.objects.generator.red.cooldown:
    range: [5, 20]
    bins: 2
  game.objects.altar.cooldown:
    range: [1, 20]
