# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metta/protobuf/sim/single_episode.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'metta/protobuf/sim/single_episode.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'metta/protobuf/sim/single_episode.proto\x12\x12metta.protobuf.sim\x1a\x1cgoogle/protobuf/struct.proto\"\x96\x01\n\x1aPureSingleEpisodeRunConfig\x12:\n\x03job\x18\x01 \x01(\x0b\x32(.metta.protobuf.sim.PureSingleEpisodeJobR\x03job\x12\x16\n\x06\x64\x65vice\x18\x02 \x01(\tR\x06\x64\x65vice\x12$\n\rallow_network\x18\x03 \x01(\x08R\rallow_network\"\x90\x02\n\x14PureSingleEpisodeJob\x12 \n\x0bpolicy_uris\x18\x01 \x03(\tR\x0bpolicy_uris\x12 \n\x0b\x61ssignments\x18\x02 \x03(\x05R\x0b\x61ssignments\x12.\n\x07\x65nv_raw\x18\xe8\x07 \x01(\x0b\x32\x17.google.protobuf.StructR\x03\x65nv\x12 \n\x0bresults_uri\x18\x04 \x01(\tR\x0bresults_uri\x12\x1e\n\nreplay_uri\x18\x05 \x01(\tR\nreplay_uri\x12\x12\n\x04seed\x18\x06 \x01(\x0cR\x04seed\x12.\n\x11max_action_millis\x18\xe9\x07 \x01(\x05R\x12max_action_time_msb\x08\x65\x64itionsp\xe8\x07')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metta.protobuf.sim.single_episode_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PURESINGLEEPISODERUNCONFIG']._serialized_start=94
  _globals['_PURESINGLEEPISODERUNCONFIG']._serialized_end=244
  _globals['_PURESINGLEEPISODEJOB']._serialized_start=247
  _globals['_PURESINGLEEPISODEJOB']._serialized_end=519
# @@protoc_insertion_point(module_scope)
