defaults:
  - common
  - wandb: metta_research
  - sim: simple
  - _self_

cmd: sim
run: ???

sim_job:
  policy_uris: ???
  simulation_suite: ${sim}
  stats_dir: ${run_dir}/stats
  stats_db_uri: ${run_dir}/stats.db
  replay_dir: ${run_dir}/replay_dir
