CHAR_TO_NAME = {
    "A": "agent.agent",
    "Ap": "agent.prey",
    "AP": "agent.predator",
    "a": "altar",
    "c": "converter",
    "n": "generator",
    "m": "mine",
    "W": "wall",
    " ": "empty",
    "s": "block",
    "L": "lasery",
    "1": "agent.team_1",
    "2": "agent.team_2",
    "3": "agent.team_3",
    "4": "agent.team_4",
    "r": "mine.red",
    "b": "mine.blue",
    "g": "mine.green",
    "R": "generator.red",
    "B": "generator.blue",
    "G": "generator.green",
    "🧱": "wall",
    "⚙": "generator",
    "⛩": "altar",
    "🏭": "factory",
    "🔬": "lab",
    "🏰": "temple",
}

NAME_TO_CHAR = {v: k for k, v in CHAR_TO_NAME.items()}
