# @package __global__

defaults:
  - override /sim: navigation
  - _self_

run: my_experiment

stats_server_uri: http://localhost:8000

trainer:
  checkpoint:
    checkpoint_interval: 50
    wandb_checkpoint_interval: 50
  simulation:
    evaluate_interval: 50
  total_timesteps: 50
